### ISSUE TITLE
OLYMPUS + FILLEPS

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#1078]
Currently unmodified OLYMPUS fails. Removing FILLEPS makes is run again. 

The issue is in "writeSatFuncScaling(...)" in WriteInit.cpp. 

Any clue @bska ? My guess is that it is related  to OLYMPUS being a oil+water case. But I stopped digging when I came down to writeSatFuncScaling(...)

**Comment by bska** [comment]
I don't have the model.  What kind of diagnostic message do you get?

**Comment by totto82** [comment]
I am sure @atgeirr or @GitPaean can help you with getting the model.

**Comment by bska** [comment]
Just a quick follow-up: If removing `FILLEPS` does make the model run, then this is likely to be related to the automatic [creation](https://github.com/OPM/opm-common/blob/b6824af640b27b2e189e58a74de1e5a1708b581d/src/opm/output/eclipse/WriteInit.cpp#L530-L532) of missing scaled end-point vectors (e.g., `SOWCR`, `SWL` etc.).  What are the saturation function keywords used in the model and what scaled end-point vectors exist?

During `assertKeyword()` we're running the saturation function initializers and finalizers.  The `FILLEPS` feature has produced errors there before, but I thought we fixed all of them in #925 (commit 8c9674856).

**Comment by totto82** [comment]
Only SWOF.

**Comment by bska** [comment]
> My guess is that it is related  to OLYMPUS being a oil+water case.

Thinking more about it, that seems plausible.  Our initializers and finalizers don't really handle two-phase models at all.  At this point my only suggestion is to remove `FILLEPS`, because we're not going to be able to fix that problem right now.

**Comment by atgeirr** [comment]
> At this point my only suggestion is to remove `FILLEPS`, because we're not going to be able to fix that problem right now.

What about a minor modification: if 2-phase, treat as no FILLEPS (and give a warning)? Would that be a sufficient workaround for now?

**Comment by bska** [comment]
> > t this point my only suggestion is to remove `FILLEPS`, because we're not going to be able to fix that problem right now.
> 
> What about a minor modification: if 2-phase, treat as no FILLEPS (and give a warning)?

That's a good idea, and easy to implement&mdash;at least if we do not want to integrate it into the `ParseContext`/`ErrorGuard` mechanism which will require changing the API.

On the other hand, I don't think we **should** use `ParseContext` and `ErrorGuard` here because this is (hopefully short-term) problem in Flow itself rather than the input deck.
