### ISSUE TITLE
Parse Errors Possibly Being Lost in Mutating Copy of ErrorGuard Object

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#1216]
The [`trim_wgname()`](https://github.com/OPM/opm-common/blob/3421b25d8ea2f0a62a4a2e2238ca46b30c4b0c93/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp#L96) helper function in `Schedule.cpp` uses/modifies a copy of an `ErrorGuard` object passed in from a caller.  Is the last parameter supposed to be a ~"mutable reference to `ErrorGuard`"~ "reference to mutable `ErrorGuard`" rather than a copy?

**Comment by joakim-hove** [comment]
You are right - it should have a mutable reference
