### ISSUE TITLE
Use dest_prefix with opm_install_python=on?

### ISSUE THREAD

**Issue by eivindjahren** [OPM/opm-common#1253]
When using the flag `opm_install_python=on` together with `DEST_PREFIX` the python package is not installed under the `DEST_PREFIX` location.

We are trying to get opm-common to install with the python bindings on our deployment pipeline.
opm-common is installed with
```sh
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DBOOST_ROOT=/path/to/boost \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_PREFIX_PATH=/prefix \
  -DCMAKE_MODULE_PATH=/prefix/install-path/cmake/Modules \
  -DCMAKE_INSTALL_PREFIX=/install-path \
  -DDEST_PREFIX=/prefix \
  -DOPM_ENABLE_PYTHON=ON \
  -DOPM_INSTALL_PYTHON=ON
```
All files are correctly installed to `/prefix/install-path` except python files which are installed to `/install-path/python2.7/site-modules/`. It would be great if we could either specify a prefix for the python modules only or that the python modules were installed in the `DEST_PREFIX` path.

**Comment by joakim-hove** [comment]
Will look into this.

**Comment by joakim-hove** [comment]
Would you give #1273 a spin - if that works for you I will merge it.

**Comment by eivindjahren** [comment]
That did the trick! Thank you!

**Comment by blattms** [comment]
I am a bit confused.
@eivindjahren Are you sure of the installation below `/prefix/install-path`? IMHO with your option all non-python files should be installed under `/install-path` as this what is specified with `CMAKE_INSTALL_PREFIX` and `CMAKE_PREFIX_PATH` is only used when searching for files and should not have any influence on he installation directory. Or am I missing something?
