### ISSUE TITLE
Warning: Warnings

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#1260]
Hello;

 as part of the 3D property refactoring I intend to merge a series of small and simple PR's (#1233, #1234, #1240, #1249). Common to all of these is that many functions now get both a `Eclipse3dProperties` and a `FieldPropsManager` argument, and then there is
```
#ifdef ENABLE_3D_TESTING
...
#endif 
```
switch which determines which of the variables is actually used. Unnless you have actually opted in for the 3D testing you will get the old behavior; jenkins uses the new behavior. As a consequence of these there will for a period be some "Undefined variable .... " warnings.

As of today only opm-common and opm-material will be directly affected by the refactoring.

**Comment by atgeirr** [comment]
How long do you expect this situation to last? Also, is it not feasible to suppress these errors?

**Comment by joakim-hove** [comment]
> How long do you expect this situation to last? 

Should be less than two weeks.

> Also, is it not feasible to suppress these errors?

They managed to build Rome - so of course it is *possible*; I have one suggestion I will look into.

**Comment by joakim-hove** [comment]
It was easier than I thought to avoid the warnings. Closing
