### ISSUE TITLE
Question: Is PORV a hard requirement?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#1271]
The new implementation of 3D properties which is right now in my machine is somewhat stricter than the existing implementation. One of the points where this stands out is in the interaction between PORV, EclipseGrid and ACTNUM. 

The construction of the grid goes something like this:

1. Read the basic geometry keywords (a suitable combination of ZCORN, COORD, DX, DY, DZ, TOPS, ...) and optionally ACTNUM from the deck and create an EclipseGrid.

2. Load all the 3D properties from the deck - including PORO, MULTPV and so on.

3. Calculate a new ACTNUM based on the newly read grid properties.

4.  Call `grid.resetACTNUM( )` with the new ACTNUM.

The important point is regarding point 3. In current master the code will check whether it has the required information to calculate `PORV`, if not it will just not update `ACTNUM`. In my local branch the code *requires* to be able to calculate `PORV` - and will fail hard if that is not possible (typically because of missing `PORO`). For real simulation decks I guess this makes no difference, but we have many tests which fail on my machine because the test-data does not include `PORO`- and then `PORV` can not be calculated.

If we require `PORV` the most natural consequence would be to go through the inline test data and add some `PORO`values - not a daunting task in any way, but it will increase the setup-complexity for new tests. I am leaning towards making `PORV` a hard requirement - but others might disagree?

**Comment by bska** [comment]
> The important point is regarding point 3. In current master the code will check whether it has the required information to calculate `PORV`,

Does that criterion also include any explicit `PORV` values entered in the `EDIT` section?

**Comment by joakim-hove** [comment]
> Does that criterion also include any explicit PORV values entered in the EDIT section?

The point is that you need to be able to calculate PORV any way or another. If you enter `PORV` in the `EDIT` section - then that is fine. For the testdata I have just updated by adding `PORO` as that was simplest.
