### ISSUE TITLE
cycle in constraints graph

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-common#130]
recently cmake started to spit the following warning at me:

```
CMake Warning at /home/and/src/opm-common/cmake/Modules/OpmSatellites.cmake:295 (add_executable):
  Cannot generate a safe runtime search path for target tutorial1 because
  there is a cycle in the constraint graph:

    dir 0 is [/home/and/src/opm-common/lib]
    dir 1 is [/home/and/src/opm-material/lib]
    dir 2 is [/home/and/src/opm-grid/lib]
    dir 3 is [/home/and/src/ert/install/lib/x86_64-linux-gnu]
      dir 5 must precede it due to runtime library [libecl.so.2]
    dir 4 is [/home/and/tmp/boost-clang-install/lib]
    dir 5 is [/home/and/src/ert/build/lib/x86_64-linux-gnu]
      dir 3 must precede it due to runtime library [libecl.so.2]
    dir 6 is [/usr/lib/openmpi/lib]

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:297 (opm_add_test)
```

without going into it too deeply, this looks like a problem caused by sibling builds. (maybe `FindERT.cmake` detects an installed version of the library as well as a sibling one?) also, this may or not be due to the fact that I compiled using ERT using GCC 5.2.1 while I used clang 3.6.2 for Dune and OPM. (given that ERT is plain-C, I consider this being the culprit somewhat unlikely.)

**Comment by atgeirr** [comment]
What should I do to reproduce?

**Comment by andlaus** [comment]
I have not too much of an idea since I have not looked into this deeply. In retrospect, I noticed that I accidentially switched between clang and gcc for some modules, but I guess that there is an independent bug somewhere: if ERT's installation directory is specified via ERT_ROOT and happens to be in a sibling directory (in my case `~/src/ert/install`), it should not add the library path twice, right?

**Comment by atgeirr** [comment]
> it should not add the library path twice, right?

Should not, but I cannot claim with certainty it doesn't (I use a `make install`ed ert).

**Comment by andlaus** [comment]
> (I use a make installed ert).

Me too, but my install prefix is a sibling of the `build` and the `devel` directories...

**Comment by atgeirr** [comment]
Is this still happening?

**Comment by andlaus** [comment]
at least not to me ;) closing
