### ISSUE TITLE
Color for warning.

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-common#132]
The color coding looks cool, but the yellow color for warning experience quite different for different terminal, probably we could use another color instead, following is a picture, for the yellow you're hardly see anything...
@atgeirr 
![norne](https://cloud.githubusercontent.com/assets/2907423/15819366/0fb9676a-2be3-11e6-85f3-b5a6ebb35b3b.png)

**Comment by atgeirr** [comment]
This obviously is less constant than I thought, a screenshot from me:

<img width="795" alt="skjermbilde 2016-06-06 kl 12 42 10" src="https://cloud.githubusercontent.com/assets/1876621/15819557/2c46aaa4-2be4-11e6-9d6b-d08bfa8ecd4c.png">


Could you experiment a little to find a good color? There are many web pages describing the codes, one of them is at

http://wiki.bash-hackers.org/scripting/terminalcodes

If you cannot find a useful color, I suggest we just use the same red as for errors. The point is just to make them stand out from the expected output, anyway.

**Comment by qilicun** [comment]
I just try a different color, the screen shot looks good. I need some more tests for different terminal.

![newcolor](https://cloud.githubusercontent.com/assets/2907423/15820285/c099749e-2be8-11e6-92a5-31970565c7d3.png)


```
--- a/opm/common/OpmLog/LogUtil.hpp
+++ b/opm/common/OpmLog/LogUtil.hpp
@@ -42,8 +42,8 @@ namespace Log {
         const std::string none = "\033[0m";
         const std::string red = "\033[31m";
         const std::string red_strong = "\033[31;1m";
-        const std::string yellow = "\033[33m";
-        const std::string yellow_strong = "\033[33;1m";
+        const std::string yellow = "\033[43m";
+        const std::string yellow_strong = "\033[43;1m";
         const std::string default_color = "\033[39m";
     }
```

**Comment by jokva** [comment]
The colour code seems right, but what RGB triple this maps to is defined by the client terminal.

**Comment by bska** [comment]
> what RGB triple this maps to is defined by the client terminal.

That's a good reason **not** to embed explicit colour schemes into the logging facilities.

**Comment by atgeirr** [comment]
> That's a good reason not to embed explicit colour schemes into the logging facilities.

... or at least making it easy to turn on/off. A parameter could easily control this (in FlowMain.hpp).

**Comment by qilicun** [comment]
What about blue?
![image](https://cloud.githubusercontent.com/assets/2907423/15822421/f548e302-2bf5-11e6-96b4-528ee11b6b6b.png)

**Comment by alfbr** [comment]
I love it, let's go blue :-)

**Comment by jokva** [comment]
This doesn't really address the issue nor improve anything. If you use a light-on-black colour scheme this will be horrible to work with.

**Comment by pgdr** [comment]
This is literally _the bikeshedding argument_.  Let's be careful that this issue is not put forth as a "programmers bikeshed" example.

It seems that changing the colors in the future should be a trivial fix if it turns out that users find the colors suboptimal.

**Comment by alfbr** [comment]
Bikeshedding indeed. Blue it should be.
