### ISSUE TITLE
Schedule::handleCOMPDAT Calls Well::updateConnections Twice

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#1336]
The [inner loop](https://github.com/OPM/opm-common/blob/7a648cae7f75a067a3bff091d3db1101fc8b1fc0/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp#L1894-L1938) of `Schedule::handleCOMPDAT()` has the following code:
```C++
if (well2->updateConnections(connections))
    this->updateWell(well2, currentStep);

if (well2->getStatus() == Well::Status::SHUT) {
    std::string msg =
        "All completions in well " + well2->name() + " is shut at " + std::to_string ( m_timeMap.getTimePassedUntil(currentStep) / (60*60*24) ) + " days. \n" +
        "The well is therefore also shut.";
    OpmLog::note(msg);
}

if (well2->updateConnections(connections))
    this->updateWell(well2, currentStep);
```
This looks unexpected to me.  Is there a reason that there are two calls, with the same argument, to [`Well::updateConnection()`](https://github.com/OPM/opm-common/blob/7a648cae7f75a067a3bff091d3db1101fc8b1fc0/opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp#L412) here?  Does the first call impact the second?

**Comment by joakim-hove** [comment]
That looks like a rouge rebase.

**Comment by bska** [comment]
> That looks like a rouge rebase.

Okay.  Which of the two calls should be removed?

**Comment by joakim-hove** [comment]
> Okay. Which of the two calls should be removed?

The latter your honor!

**Comment by bska** [comment]
> > Okay. Which of the two calls should be removed?
> 
> The latter

Aye!  Unless you wish to do it I'll prepare a quick PR with the change.
