### ISSUE TITLE
Fails to parse ROCK if ROCKOPTS use ROCKNUM

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#1357]
This is copied over from opm-parser: https://github.com/OPM/opm-parser/issues/1228

If a deck declares item 3 of ROCKOPTS to ROCKNUM, the number of records in the ROCK keyword is no longer NTPVT as declared in
https://github.com/OPM/opm-parser/blob/master/lib/eclipse/share/keywords/000_Eclipse100/R/ROCK

but rather the max (I suppose) of the ROCKNUM region parameter.

Trying to build a deck object of such an input file gives an exception depending on what comes next after the ROCK keyword, as it does not know how many records to parse, example error message:
```
Failed to parse keyword: ROCK
Starting at location: ....

Inner exception: Malformed floating point number PVTW
```
Is this feasible to fix/mitigate? (I don't need to support ROCK/ROCKNUM, I only need to be able to parse other portions of the deck)

**Comment by joakim-hove** [comment]
@berland 

Thank you for the report - that was a new one. To fix this properly would be a large job, the band aid fix would be to set `"size": "unknown"` - that should work but it is unfortunate with these unknown size keywords ... But - I guess we can do that.

> Disclaimer: Only tested with opm-common with the tag release/sunbeam/2019.02

I am afraid it still applies :-(

**Comment by berland** [comment]
`src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/ROCK` already declares `"size": "UNKNOWN"`

Band-aid maybe more difficult then.

**Comment by joakim-hove** [comment]
Details details..!

**Comment by berland** [comment]
This deck is valid E100, but fails with OPM-common's parser:

It does not fail if the number of unique ROCKNUM values are larger than NTPVT it seems.
```
RUNSPEC
DIMENS
  1 1 2 / 
OIL
WATER
GAS
START
  1 'JAN' 2100 /
TABDIMS
   1* 2 10* 1 /  -- 13th item here is NTROCC, number of rock tables
-- NTPVT not equal to NTROCC

GRID
DX
   10 10/ 
DY
   10 10 /
DZ
   50 50/ 
TOPS
   1000 1050 /
PORO
   0.3 0.2 /
PERMX
   100 200/
PERMY
   100 200/
PERMZ
   100 200 /

PROPS

ROCKOPTS
 2* 'ROCKNUM' /

SWOF
0 0 1 0 
1 1 0 0 
/

SGOF
0 0 1 0 
1 1 0 0 
/

DENSITY
  800 1000 1.2 /
  800 1000 1.2 /

ROCK
  100 0.0001 /

PVTW
  1 1 0.0001 0.2 0.00001 /
  1 1 0.0001 0.2 0.00001 /
PVDO
   100 1   1   
   150 0.9 1 / 
   100 1   1   
   150 0.9 1 / 
PVDG
   100 1 1 
   150 0.9 1 / 
   100 1 1 
   150 0.9 1 / 

REGIONS

ROCKNUM
 1  1 / 

SOLUTION
EQUIL
   1000    100     1040    0   1010      0 / 
```

**Comment by berland** [comment]
Has this been solved? Not immediately able to reproduce failure in testing/2020.3/rc1

**Comment by berland** [comment]
Not reproducible. Closing.
