### ISSUE TITLE
Wrong ordering of `SimulationDataContainer::saturation()` assumed in euclidianNormSquared

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#136]
Due to missing documenation I have to ask:
How are the saturation ordered for `SimulationDataContainer::saturation()`? All saturations of the first cell before the saturations of the next one, or all saturations of the first phase before the ones of the next phase?

**Comment by atgeirr** [comment]
> All saturations of the first cell before the saturations of the next one

This is the correct ordering. I have been toying with the idea of switching, but I think we won't.

**Comment by blattms** [comment]
Then we have uncovered another bug in the parallelization. Somehow I or somebody else assumed that the ordering is the same as in the AutodiffBlocks. As that assumption is wrong, we have to fix euclideanNorm at https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1127-L1152 as it used for saturation at the following places 
https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#1653, and https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#1659.

**Comment by blattms** [comment]
@atgeirr Were are these values of 'SimulationDataContainer::saturation()" set? I could not find the place in the code and would love to double check!

**Comment by blattms** [comment]
The bug is of course in opm-simulators. Opening it there.
