### ISSUE TITLE
Irregular Grid

### ISSUE THREAD

**Issue by HygorCosta** [OPM/opm-common#1403]
It's possible in Flow create a grid like this ?

![Irregular Grid](https://user-images.githubusercontent.com/31241360/72174497-aa287a80-33b8-11ea-81f6-f79c6aa7cd28.png)

**Comment by OPMUSER** [comment]
No - this type of grid is not possible either with OPM Flow or the
commercial simulator. However, in the commercial simulator one can use
Local Grid Refinements ("LGR") to accomplish something like this, the
down side is that each LGR is a separate simulation running concurrently
with the main grid.

OPM User
opmuser0@gmail.com
