### ISSUE TITLE
Error in Documentation Pg 212,213

### ISSUE THREAD

**Issue by dabiged** [OPM/opm-common#1486]
SURFACT and SURFACTW pages have clashes between the table at the top and the text.

On both pages the table at the top has an orange RUNSPEC box, indicating that the KEYWORD is not supported. 
However the text does not explicitly state that the keyword is NOT supported by flow as on other pages.
Either the table color or the text is incorrect, I am unsure which.

**Comment by OPMUSER** [comment]
SURFACT and SURFACTW keywords are recognized by the parser but ignored by OPM Flow. I have added the following text for these two keywords version 2020-04 of the manual:

`This keyword is ignored by OPM Flow and has no effect on the simulation.`
