### ISSUE TITLE
error when compiling opm-common

### ISSUE THREAD

**Issue by tskille** [OPM/opm-common#1513]
I'm using RH7 + devtoolset-7

commit > 3a69bcbf4adbd844935872f1e800bb19b245ae0b ?? Merge pull request #1503 from joakim-hove/wellsegments-alt-cons

compiles without error

next commit 

> 09595b98adb97b79c9147af69a75b492b0c81b56 Merge pull request #1495 from joakim-hove/opmpack-copy-restart

compiles with the following error

/project/multiscale/OPM/tskille/flow_daily_rh7/opm-common/examples/opmpack.cpp: In function 'void copy_file(const std::experimental::filesystem::v1::path&, std::experimental::filesystem::v1::path, const std::experimental::filesystem::v1::path&)':
/project/multiscale/OPM/tskille/flow_daily_rh7/opm-common/examples/opmpack.cpp:79:21: error: 'relative' is not a member of 'fs'
         fname = fs::relative(fname, source_dir);
                     ^~~~~~~~
make[2]: *** [CMakeFiles/opmpack.dir/build.make:63: CMakeFiles/opmpack.dir/examples/opmpack.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2206: CMakeFiles/opmpack.dir/all] Error 2

Other who have the same issue ?

**Comment by akva2** [comment]
yes. the fs::relative method is not in the filesystem TS implemented in gcc 7. for now you can switch to devtoolset-8.

**Comment by blattms** [comment]
So we are actually demanding gcc-8?

**Comment by akva2** [comment]
not anymore.
