### ISSUE TITLE
WWIP keyword in Summary section not recognized

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-common#1553]
And simulation terminates when keyword is present. The keyword should trigger output og Water potential injection rate, which may be useful in current group control efforts. The issue probably also concerns similar keywords (e.g., group and field potentials, production potentials, oil potentials).

**Comment by joakim-hove** [comment]
How does it terminate?

**Comment by alfbr** [comment]
The parser bails out on the first record following after keyword, which is a well with a terminating slash, with the "not formatted/recognized as valid keyword" message. Hence, I believe the parser needs to be aware of the format of the keyword in a json scheme to handle it without bailing.

**Comment by alfbr** [comment]
Please note, that actually outputting the corresponding summary output is quickly becoming prioritized as it is necessary for group control bug hunting.

**Comment by joakim-hove** [comment]
Ok - message received!

**Comment by joakim-hove** [comment]
> The parser bails out on the first record following after keyword, which is a well with a terminating slash, with the "not formatted/recognized as valid keyword" message.

I have looked briefly on this now. The parser should recognize `WWIP` as a well summary keyword already; i.e. the following should parse just fine:
```
SUMMARY

WWIP
/

WWIP
   'W1'  'W2'  'W3' /
```
But if your `WWIP`keyword is different it might be a case of slight "conflict" in the input specification. It would help if you could post some lines of the relevant `SUMMARY` section. The code already supports the `WWPI` keyword; `WWPI` and `WWIP` should be aliases to eachother - so supporting `WWIP` all the way should be simple when the parsing issue has been resolved.

**Comment by alfbr** [comment]
It looks like this:

```
WWIP
'W1'  /
'W2'  /
'W3' /
/
```

**Comment by joakim-hove** [comment]
Ok - that is 'wrong' - it should be:
```
WWIP
  'W1' 'W2' 'W3' /
```
What to do about it???

**Comment by alfbr** [comment]
If that is correct, we need to fix the deck. I will check.

**Comment by bska** [comment]
>> it should be:
>> ```
>> WWIP
>>   'W1' 'W2' 'W3' /
>> ```
>
> If that is correct, we need to fix the deck.

Just to add to what @joakim-hove said: I too would expect the `WWIP` (and `WWPI`) summary keyword to have a single record specifying individual well names (or none at all to request output for all wells).  This is the same format used, e.g., for `WBHP` and `WOPT`.

**Comment by bska** [comment]
@alfbr : Do you still experience problems with the `WWIP` summary vector?

**Comment by alfbr** [comment]
> @alfbr : Do you still experience problems with the `WWIP` summary vector?

The error was in the deck, so this issue can be closed. However, it does illustrate one example where diagnostic output from Flow could potentially be more informative, guiding the user to what is wrong.
