### ISSUE TITLE
Output of ISEG - I do not understand

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#1585]
When trying to initialize the Schedule object from the restart file I am struggling with the MSW cases. Specifically I am looking at this code in [`AggregateMSWData.cpp:442`](https://github.com/OPM/opm-common/blob/master/src/opm/output/eclipse/AggregateMSWData.cpp#L442):
```C++
442:  template <class ISegArray>
443:         void staticContrib(const Opm::Well&       well,
444:                             const std::vector<int>& inteHead,
445:                             ISegArray&              iSeg)
446:          {
447:              using Ix = ::Opm::RestartIO::Helpers::
448:                  VectorItems::ISeg::index;
449:  
450:              if (well.isMultiSegment()) {
451:                 //loop over segment set and print out information
452:                  const auto& welSegSet     = well.getSegments();
453:                 const auto& completionSet = well.getConnections();
454:                  const auto& noElmSeg      = nisegz(inteHead);
455:                  auto orderedSegmentNo = segmentOrder(welSegSet);
456:                  std::vector<int> seg_reorder (welSegSet.size(),0);
457:                  for (std::size_t ind = 0; ind < welSegSet.size(); ind++ ){
458:                      const auto s_no = welSegSet[orderedSegmentNo[ind]].segmentNumber();
459:                      const auto s_ind = welSegSet.segmentNumberToIndex(s_no);
460:                      seg_reorder[s_ind] = ind+1;
460:                  }
461:                  for (std::size_t ind = 0; ind < welSegSet.size(); ind++) {
462:                      const auto& segment = welSegSet[ind];
463:  
464:                      auto segNumber = segment.segmentNumber();
465:                      auto iS = (segNumber-1)*noElmSeg;
466:                      iSeg[iS + Ix::SegNo]          = welSegSet[orderedSegmentNo[ind]].segmentNumber();
467:                      iSeg[iS + Ix::OutSeg]         = segment.outletSegment();
468:                      iSeg[iS + Ix::InSegCurBranch] = (inflowSegmentCurBranch(well.name(), welSegSet, ind) == 0) ? 0 : welSegSet[inflowSegmentCurBranch(well.name(), welSegSet, ind)].segmentNumber();
469:                      iSeg[iS + Ix::BranchNo]       = segment.branchNumber();
470:                      iSeg[iS + 4] = noInFlowBranches(welSegSet, ind);
471:                      iSeg[iS + 5] = sumNoInFlowBranches(welSegSet, ind);
472:                      iSeg[iS + 6] = noConnectionsSegment(completionSet, welSegSet, ind);
473:                      iSeg[iS + 7] = sumConnectionsSegment(completionSet, welSegSet, ind);
474:                      iSeg[iS + 8] = seg_reorder[ind];
475:  
476:                      iSeg[iS + Ix::SegmentType] = segment.ecl_type_id();
477:                      if (! isRegular(segment)) {
478:                          assignSegmentTypeCharacteristics(segment, iS, iSeg);
479:                      }
480:                  }
481:              }
482:              else {
483:                  throw std::invalid_argument("No such multisegment well: " + well.name());
484:              }
485:          }
486:      } // ISeg
```

I don't know the details of the format- so I might be wrong; but to me this code looks quite peculiar - and I suggest that it maybe is incorrect. What I am thinking of specifically is:

1. At line 455 a index mapping is created - as I understand it maps from the plain segment index to branch ordered index.
2. At line 462 we fetch segment number `ind` - that segment variable is used in lines 467, 469 and 476.
3. At line 466 we use the reorder map and fetch a segment from there - and then store that segment number.

Rewriting this slightly we have:
```C++
for (std::size_t ind = 0; ind < welSegSet.size(); ind++) {
     const auto& segment = welSegSet[ind];
     const auto& reorder_segment = welSegSet[ orderedSegmentNo[ind] ];
     auto iS = (segment.segmentNumber() -  1)*noElmSeg;

     iSeg[iS + Ix::SegNo]       = reorder_segment.segmentNumber();
     iSeg[iS + Ix::OutSeg]      = segment.outletSegment();
     iSeg[iS + Ix::BranchNo]    = segment.branchNumber();
     iSeg[iS + Ix::SegmentType] = segment.ecl_type_id();

}
```
to me it looks weird that one `ISEG` block should have a mix of information from `segment` and `reorder_segment`? If I just replace the `reorder_segment` with `segment` when writing the file my restart loading seems to work (much better at least). Maybe the problem is that what is is written in `iSeg[iS + Ix::SegNo]` really is not segment number - but something else, and the segmen number should just be inferred from the location in the vector? From test it seems the same value is written in `iSeg[iS + 8]`

There might be several things here I do not understand; but to me the whole segment  reorder mapping seems unnecessary - because everything is written out in blocks given by the segment number - and that is not updated in the process. So apart from the `seg_reorder[ind]` written out at line 474 I don't see that the reordering has any effect?  

A PR demonstrating my suggested change is here: #1586

**Comment by joakim-hove** [comment]
Ping

**Comment by bska** [comment]
It may be possible to simplify the mappings here, but some kind of mapping is nevertheless needed.  The values in ISEG[0] are essentially ordered by branches and we do need this in order to restart ECLIPSE from Flow.

**Comment by joakim-hove** [comment]
> The values in ISEG[0] are essentially ordered by branches and we do need this in order to restart ECLIPSE from Flow.

Thank's for answering - but I still understand this - I am sorry. If the current is as it should be then I at least think the named `Ix::SegNo` should be renamed to something like `Ix::SegNoBranchOrderedSegment`. It looks quite weird to me.

I'll :phone: later.
