### ISSUE TITLE
I am not able to build the newest master on my Ubuntu 16.04

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#1644]
In file included from /home/thsa/poly/opm-common/src/opm/io/eclipse/SummaryNode.cpp:26:0:
/home/thsa/poly/opm-common/opm/io/eclipse/SummaryNode.hpp:22:14: error: expected ‘{’ before ‘::’ token
 namespace Opm::EclIO {
              ^
/home/thsa/poly/opm-common/opm/io/eclipse/SummaryNode.hpp:22:16: error: ‘EclIO’ in namespace ‘::’ does not name a type
 namespace Opm::EclIO {
                ^
/home/thsa/poly/opm-common/src/opm/io/eclipse/SummaryNode.cpp:30:32: error: ‘Opm::EclIO’ has not been declared
 constexpr bool use_number(Opm::EclIO::SummaryNode::Category category) {
                                ^
/home/thsa/poly/opm-common/src/opm/io/eclipse/SummaryNode.cpp:30:71: error: expected ‘,’ or ‘;’ before ‘{’ token
 constexpr bool use_number(Opm::EclIO::SummaryNode::Category category) {
                                                                       ^
/home/thsa/poly/opm-common/src/opm/io/eclipse/SummaryNode.cpp:115:1: error: expected ‘}’ at end of input
 }
 ^
/home/thsa/poly/opm-common/src/opm/io/eclipse/SummaryNode.cpp:115:1: error: expected ‘}’ at end of input

**Comment by akva2** [comment]
gcc5 is no longer supported, gcc7 is minimum.

**Comment by totto82** [comment]
Sorry. I forgot. I was building on my ubuntu subsystem in windows and forgot I still used < gcc7.
