### ISSUE TITLE
Quoting in opm.tools.TimeVector

### ISSUE THREAD

**Issue by berland** [OPM/opm-common#1680]
`opm.tools.TimeVector` does not handle quoting correctly for `UDQ` statements:

Run this
```python
import datetime
from opm.tools import TimeVector

with open("udq.sch", "w") as fh: 
    fh.write("""
UDQ
  DEFINE FUGTARG  7200000   - FGLIR /
  UNITS  FUGTARG  SM3/DAY  /
/
""")
schedule = TimeVector(datetime.datetime.now())
schedule.load("udq.sch", datetime.datetime.now())
print(schedule)
```
Which prints
```
DATES
  3 'APR' 2020/
/

UDQ
   'DEFINE' 'FUGTARG' '7200000' '-' 'FGLIR' /
   'UNITS' 'FUGTARG' 'SM3/DAY' /
/
```
The quoting that goes into the final UDQ statement gives the following errors from E100:
```
@--  ERROR FROM PROCESSOR 1 AT TIME     8830.0   DAYS    ( 4-DEC-2019):
@           OPERATION   NOT RECOGNISED FOR THE UDQ KEYWORD                 
 @           IN RECORD 1 OF THE UDQ DATA.                                   

@--  ERROR FROM PROCESSOR 1 AT TIME     8830.0   DAYS    ( 4-DEC-2019):
@           OPERATION   NOT RECOGNISED FOR THE UDQ KEYWORD                 
 @           IN RECORD 2 OF THE UDQ DATA.    
```

**Comment by joakim-hove** [comment]
OK - bug noted.

**Comment by joakim-hove** [comment]
OK - this is a bug in the writing of DeckKeywords, and not related to the `TimeVector` as such. Could you try to manually edit the file and *only* remove quotes on the first tokens, i.e. 
```
UDQ
   DEFINE  'FUGTARG' '7200000' '-' 'FGLIR' /
   UNITS  'FUGTARG' 'SM3/DAY' /
/
```

**Comment by berland** [comment]
That seems insufficient. The only allowed quotes are around `FUGTARG` and `SM3/DAY`, otherwise the quotes generate error messages from E100. Spaces around minus sign arek ok.

**Comment by joakim-hove** [comment]
> The only allowed quotes are around FUGTARG and SM3/DAY, otherwise the quotes generate error messages from E100. Spaces around minus sign are ok.

OK - thanks; hopefully this can be solved.

**Comment by joakim-hove** [comment]
OK - how about no quotes at all:

```
UDQ
   DEFINE   FUGTARG   7200000  -   FGLIR /
   UNITS  FUGTARG SM3/DAY /
/
```
?

**Comment by berland** [comment]
That works fine too!
