### ISSUE TITLE
2020-04 Manual: Missing Keywords

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#1708]
Another release so time to check the never ending keyword list. The following keywords have no definitions as far as I can see. Do we wish to fix this for the new release.

![2020-04-15 15_38_11-OPM_Flow_Documentation_2020-04_Rev-A ods - LibreOffice Calc](https://user-images.githubusercontent.com/17958927/79408613-55575a00-7fce-11ea-9e18-cfce9397b88a.png)

**Comment by joakim-hove** [comment]
I will add the keywords: `GETDATA, OUTSOL, PLYESAL, PLYKRRF, RADFIN, SAMG, WELMOVE` for the remaining keywords I do not have the definition.

**Comment by OPMUSER** [comment]
@joakim-hove You do  now, check company email ;-)

**Comment by joakim-hove** [comment]
OK - these keywords should be added here: https://github.com/OPM/opm-simulators/pull/2544 with a corresponding missing feeatures here: https://github.com/OPM/opm-simulators/pull/2544

**Comment by OPMUSER** [comment]
They don't show here:

https://github.com/OPM/opm-simulators/blob/master/opm/simulators/flow/MissingFeatures.cpp

**Comment by akva2** [comment]
that's because the PR has not been merged yet...

**Comment by OPMUSER** [comment]
Sorry for the noise.
