### ISSUE TITLE
2020-04 Manual: Multi-Segment Wells Keyword Status

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#1714]
Has (or will) the WSEGVALV keyword been implemented in the 2020-04 release and is the keyword status shown below correct?

![2020-04-17_OPM_Flow_Documentation_2020-04_Rev-A_MULTI-SEGMENT_WELLS](https://user-images.githubusercontent.com/17958927/79536631-17803180-80b3-11ea-8050-cb619bab879b.png)

**Comment by GitPaean** [comment]
Hi, @OPMUSER , WSEGVALV has been implemented and merged already. It is supported now.

**Comment by OPMUSER** [comment]
Tusen takk

OPM User
opmuser0@gmail.com
