### ISSUE TITLE
2020-04 Manual: Keywords that should be in Missing Features.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#1720]
I think all the keywords below should be in the Missing Features list, plus the PRVD keyword needs to be defined as well. The only one I'm not sure of is the SPOLY keyword, can somebody confirm the status of this keyword.

![image](https://user-images.githubusercontent.com/17958927/79733329-7fd74900-8327-11ea-8fae-1d10b70daffe.png)

**Comment by GitPaean** [comment]
I believe SPOLY should be supported.

**Comment by GitPaean** [comment]
https://github.com/OPM/opm-simulators/blob/9625d0b48c172b0915487ef5ace22052aa9fa0c4/ebos/eclproblem.hh#L2722

**Comment by GitPaean** [comment]
But it looks like the Unit system related to polymer concentration is a little messy, will try to come up with a PR with it. But it should not impact the result. `SPOLY` is supported.

**Comment by OPMUSER** [comment]
@GitPaean okay I have changed the status of SPOLY to supported - thank you.

**Comment by OPMUSER** [comment]
Fixed the keywords I know should be in Missing-Features PR, added GECONT, changed RIVRDIM to RIVRDIMS, added RPTSOL, RSSPEC, changed SCPDIMS to SCDPDIMS, as well as fixing the VISAGE and WALKALIN spreadsheet errors. The list is now:

![image](https://user-images.githubusercontent.com/17958927/79832266-a9ea4300-83db-11ea-9d0b-ceefdcb84a48.png)


The PR keywords are marked as PR in the Check column.

**Comment by OPMUSER** [comment]
Fixed the keywords I know should be in Missing-Features PR, added GECONT, changed RIVRDIM to RIVRDIMS, added RPTSOL, RSSPEC, changed SCPDIMS to SCDPDIMS, as well as fixing the VISAGE and WALKALIN spreadsheet errors. The list is now:



The PR keywords are marked as PR in the Check column.
