### ISSUE TITLE
Compiler warning / bug in output/data/Groups.hpp

### ISSUE THREAD

**Issue by timokoch** [OPM/opm-common#1756]
I get the following warning when compiling OPM with clang 6
```
../opm/output/data/Groups.hpp:114:25: warning: comparison of address of 'this->currentGasInjectionConstraint' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        return ((&this->currentGasInjectionConstraint != nullptr) && (&this->currentGasInjectionConstraint != nullptr)
                  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~~~~
../opm/output/data/Groups.hpp:114:78: warning: comparison of address of 'this->currentGasInjectionConstraint' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        return ((&this->currentGasInjectionConstraint != nullptr) && (&this->currentGasInjectionConstraint != nullptr)
                                                                       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~~~~
../opm/output/data/Groups.hpp:115:20: warning: comparison of address of 'this->currentProdConstraint' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        && (&this->currentProdConstraint != nullptr));
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~    ~~~~~~~
```

Looks like the compiler is right and these checks are buggy. These values are actually data members of some enumeration type `Opm::Group::ProductionCMode` or `Opm::Group::InjectionCMode`. And this is taking addresses of potentially uninitialized members and compares this will `nullptr`, looks sketchy... 

I don't know exactly what this does but maybe initializing these members with  `Opm::Group::ProductionCMode::None` and then comparing to None could be the fix.

**Comment by bska** [comment]
I'm closing this issue as the `data::Group::has()` function was removed in #1757.

**Comment by timokoch** [comment]
@bska We are building a Dumux release on top of the 2020.04 release. Any chance this can be backported?

**Comment by joakim-hove** [comment]
> We are building a Dumux release on top of the 2020.04 release. Any chance this can be backported?

OK - I'll backport

**Comment by timokoch** [comment]
@joakim-hove thanks!
