### ISSUE TITLE
invalid write in src/opm/io/eclipse/ESmry.cpp

### ISSUE THREAD

**Issue by berndflemisch** [OPM/opm-common#1813]
In line 855, there's
```cpp
    char* numstr  = new char[12];
```
and in line 883, it's
```cpp
            numstr[12]='\0';
```

I'd prepare a patch but I don't know if it's better to increase the size or to decrease the index.

**Comment by berndflemisch** [comment]
Plus I don't understand why this needs a `new`. It's deleted in the same function at the end.

**Comment by tskille** [comment]
@berndflemisch thanks for submitting this issue. I have prepared a PR https://github.com/OPM/opm-common/pull/1815 which fixes this error

**Comment by bska** [comment]
PR #1815 was merged.  Is this still a problem, @berndflemisch ?  If not, please close the issue.

**Comment by berndflemisch** [comment]
All good, thanks!
