### ISSUE TITLE
Schedule::filterConnections Runs Filtering Three Times

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#1998]
The [`Schedule::filterConnections()`](https://github.com/OPM/opm-common/blob/fcdc57d92baa18cb4ee199425b59340737ea8513/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp#L1274) member function is implemented thus
```C++
void Schedule::filterConnections(const ActiveGridCells& grid) {
    for (auto& dynamic_pair : this->wells_static) {
        auto& dynamic_state = dynamic_pair.second;
        for (auto& well_pair : dynamic_state.unique()) {
             if (well_pair.second)
                well_pair.second->filterConnections(grid);
        }
    }

    for (auto& dynamic_pair : this->wells_static) {
        auto& dynamic_state = dynamic_pair.second;
        for (auto& well_pair : dynamic_state.unique()) {
            if (well_pair.second)
                 well_pair.second->filterConnections(grid);
        }
    }

    for (auto& dynamic_pair : this->wells_static) {
        auto& dynamic_state = dynamic_pair.second;
        for (auto& well_pair : dynamic_state.unique()) {
            if (well_pair.second)
                well_pair.second->filterConnections(grid);
        }
    }
}
```
Unless I'm missing something, this appears to be three copies of the same loop.  Is there a reason for this strategy?

**Comment by joakim-hove** [comment]
Looks like a rebase gone completely wrong. I see no reason for this

**Comment by bska** [comment]
> Looks like a rebase gone completely wrong. I see no reason for this

Okay, I'm working in this area now to add infrastructure for `WELPI`.  I'll remove two of the loops as part of that.
