### ISSUE TITLE
Odering of wells from Schedule::getWells during a simulation.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#2009]
Is there some kind of ordering guarantee that we can/should rely on?

E.g. if at some t_1 during the simulation two wells w_1 and w_2 are at index i_1 and i_2 (i_1 < i_2) of the `Schedule::getWells()` container, then for any time  t_2 > t_1 where both wells are present at indices j_1 and j_2, respectively, j_1 < j_2 also holds?

**Comment by blattms** [comment]
Including the ordering of all wells from `Schedule::getWellsatEnd()`

**Comment by bska** [comment]
The wells always come in order of appearance in `WELSPECS`.

**Comment by atgeirr** [comment]
It may be a safer choice to associate well data will well names, instead of depending on ordering/indices.

**Comment by blattms** [comment]
Thanks. great that there is an insertion index. Maybe we should sometime make use of that to save the string lookups.
