### ISSUE TITLE
WIP Schedule logging

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#2010]
Handling Schedule keywords 
In /path/to/file ...

Starting report step N at 27-01-1999 line 2671
Reading WCONPROD at line 1098
Reading WCONHIST at line 1256
Reading WELSPECS
Report step N completed at 30-01-1999 line 3000

Starting report step N+1 at 30-01-1999
...
Report step N+1 completed

**Comment by bska** [comment]
> ```
> In /path/to/file ...
> 
> Starting report step N at 27-01-1999 line 2671
> [...]
> Report step N completed at 30-01-1999 line 3000
> ```

I like that strategy and I think it'll be a significant improvement over the current logging output.  Just one minor point about the file/line information.  It's unlikely to happen in practice, but I suppose it's possible that there could be an `INCLUDE` statement somewhere in the middle of the `SCHEDULE` data meaning that the not all data may refer to the same file.   Do we want to emit notifications when the source file changes too?

**Comment by joakim-hove** [comment]
>  Do we want to emit notifications when the source file changes too?

That is the intention yes.

**Comment by bska** [comment]
@joakim-hove : Is this issue still relevant now that #2013 has been merged?

**Comment by joakim-hove** [comment]
Not relevant.
