### ISSUE TITLE
CMake errors in downstream module

### ISSUE THREAD

**Issue by berndflemisch** [OPM/opm-common#2091]
I'm on Ubuntu 2020.10 and with CMake 3.16.3. When building Dumux on top of opm-common and opm-grid, I get CMake errors like
```
CMake Error in examples/liddrivencavity/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "example_ff_liddrivencavity":

    "SYSTEM"
```
for all tests. This happens for opm master and 2020.10 release branch, the 2020.04 release branch is fine.

[console_output.txt](https://github.com/OPM/opm-common/files/5499848/console_output.txt)
[CMakeOutput.log](https://github.com/OPM/opm-common/files/5499850/CMakeOutput.log)
[CMakeError.log](https://github.com/OPM/opm-common/files/5499851/CMakeError.log)

**Comment by bska** [comment]
@akva2 : Could this in any way be related to commit 70d13b7 (PR #1954)?

**Comment by berndflemisch** [comment]
Removing the `SYSTEM` from line 79 of `CMakeLists.txt` solves the issue for me.

**Comment by akva2** [comment]
yes that would be the trigger. cmake is being stupid here, but i've added a PR with a workaround.

**Comment by berndflemisch** [comment]
Thank you so much for the fast help! It would be supernice if you could backport #2093 to the 2020.10 release branch.

**Comment by akva2** [comment]
it's already backported.

**Comment by berndflemisch** [comment]
Perfect, thanks! I'm not used to not getting notified automatically of every Git fart like for my "closer" projects.
