### ISSUE TITLE
cmake error when build opm module chain from scratch

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-common#211]
When I checkout all current master modules (and DUNE 2.4) then I get an error in opm-output because opm-common seems not to be included in the include path passed to the compiler. 
```
opm-output/opm/test_util/summaryIntegrationTest.cpp:21:38: fatal error: opm/common/ErrorMacros.hpp: No such file or directory
 #include <opm/common/ErrorMacros.hpp>
```

**Comment by bska** [comment]
This may be related to #202.  PR #210 (merged just moments ago) restores my ability to build the chain from scratch, but I'm not sure that we understand the issue fully yet.  Would you mind trying to rebuild your chain with #210 in place to see if you at least regain the ability to build?

**Comment by dr-robertk** [comment]
Thanks, indeed it is fixed now.
