### ISSUE TITLE
Expose ParseContext::ignoreKeyword to Python

### ISSUE THREAD

**Issue by berland** [OPM/opm-common#2262]
The ignoreKeyword() function in a ParseContext  object does not seem to be exposed to Python

https://github.com/OPM/opm-common/blob/47a7f15efce04f6ab8d12f5377cba0b223c95a65/src/opm/parser/eclipse/Parser/ParseContext.cpp#L136

This function is interesting for pure parsing application when opm-common is only used to (hopefully) quickly extract a subset of the data involved in a deck.

**Comment by joakim-hove** [comment]
OK: there is a fix for just what the doctored here: https://github.com/OPM/opm-common/pull/2316

**But 1:** The `ParseContext::ignoreKeyword()` is meant to ignore *unknown* keywords, and not ignore already recognized keywords. So `ParseContext::ignoreKeyword("ZCORN")` will still load the `ZCORN` keyword - so I am afraid there is no simple speed up here.

**But 2:** When the parser functionality was written care was taken to make the available keywords dynamic; i.e. you can instantiate an empty parser and then selectively add keywords; i.e. you can create a custom parser which only parses the grid related keywords. This functionality has not been much used - the main modus operandi is to just instantiate and use a parser which can parse all the known keywords, and functionality for dynamic assembly of a parser could need some love (and Python exposure) - not a large task - but more than #2316. A valuable general improvement.

**But 3:** One of the main challenges when parsing the .DATA files is to recognize when one keyword ends, and another starts - maybe we have made some bad decisions on that functionality? Anyway if you have made a custom parser which only recognizes the few keywords you are interested in you might experience that the parser gets confused by the other keywords in the deck.

**Comment by berland** [comment]
Thanks! I am clinging to the hope that by ignoring the GRID keyword, the INCLUDE statements in that section then won't get processed at least, but that might still be wrong.

**Comment by alfbr** [comment]
This has now been implemented, albeit somewhat differently. Have you tested it? If so, please consider closing the ticket.

**Comment by berland** [comment]
Issue 260 in ecl2df has not been resolved, so not fully tested, but the implementation in opm seems good enough to warrant closing this.
