### ISSUE TITLE
COMPDAT Handling Uses Moved-From Object

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#2277]
The [`Schedule::handleCOMPDAT()`](https://github.com/OPM/opm-common/blob/c9908df91417e17e58568b9c9525d29b7ef435d4/src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp#L147) function has the following [statements](https://github.com/OPM/opm-common/blob/c9908df91417e17e58568b9c9525d29b7ef435d4/src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp#L162-L167)
```C++
if (well2->updateConnections(connections, *handlerContext.grid_ptr, handlerContext.fp_ptr->get_int("PVTNUM"))) {
    this->updateWell(std::move(well2), handlerContext.currentStep);
    wells.insert( name );
}

if (connections->empty() && well2->getConnections().empty()) {
```
Here, the `well2->getConnections()` call will read from a moved-from `well2` object if the earlier `updateConnections()` call returns `true`.  That's undefined behaviour.

**Comment by joakim-hove** [comment]
Thanks. Fix here: https://github.com/OPM/opm-common/pull/2278
