### ISSUE TITLE
Confusing Report Step Labeling in "Initializing ..." Message

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#2391]
I just looked more closely at the `.PRT` file of a simulation run and I noticed the following messages

> ```
> Complete report step 1 (30.0 DAYS) at 2018-12-01 (0.0 DAYS)
> 
> [...]
> 
> Initializing report step 6/6 at 2019-07-01 (151.0 DAYS) - line 283
> Complete report step 6 (62.0 DAYS) at 2019-09-01 (242.0 DAYS)
> 
> Initializing report step 7/6 at 2019-09-01 (242.0 DAYS) - line 283
> ```

Report step `7/6` looks weird.  For the record, this simulation model has 6 report steps in total.  Since this is a user-facing issue I'd prefer that it be fixed in time for the 2021.04 release.

**Comment by joakim-hove** [comment]
I know - it is on the list

**Comment by bska** [comment]
> it is on the list

Cool.  By the way, `242.0 DAYS` looks weird too since 151 + 62 = 213.

**Comment by bska** [comment]
Closing as solved in #2392.
