### ISSUE TITLE
Official Debian packages

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#2435]
This is for people interested in this effort. The current state is on [salsa.debian.org](https://salsa.debian.org/blattms/opm-common). This is currently being finalized (mainly coming up with good package descriptions), and will then be submitted to debian.

**Comment by blattms** [comment]
I intend to write something about the packaging process (git-bulldpackage) on the wiki in due time. For now just note, that the contents of master is a snapshot of the official OPM repository (stripped are embedded external codes, any packaging stuff, jenkins, travis, etc). The only changes happening are and will be below debian which contains the packaging information (changes to the official code will be via quilt patches below debian/patches).

**Comment by atgeirr** [comment]
Happy to see it!

**Comment by blattms** [comment]
For completeness: corresponding [ITP bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987381)

**Comment by blattms** [comment]
And then hell broke loose when we ran tests on i386 architecture, because of (naive?) floating point comparisons in some tests. See https://salsa.debian.org/science-team/opm-common/-/jobs/1615174

**Comment by blattms** [comment]
For updates of the process see OPM/opm-simulators#3172
