### ISSUE TITLE
Defaulted Reference Depth Causes Problem in Well Without Any Connections

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#2442]
I recently tried to simulate the `Gassnova_simulation_model_FF_SMEAHEIA_21.DATA` in the "Smeaheia" simulation model dataset from the [CO2 DataShare](https://co2datashare.org/dataset/smeaheia-dataset).  This simulation model declares its wells as follows
```
WELSPECS
-- ...
 'WP3'     'PROD'   70  220  1*  'OIL'  0.2 /
 'WP4'     'PROD'   90  220  1*  'OIL'  0.2 /
/
```
meaning the BHP reference depth (item 5) is defaulted.  This item is defaulted in all wells, but I'll concentrate specifically on the wells `WP3` and `WP4` here.  In the case of the reference depth being defaulted, we of course pick   the cell centre depth in the wells' [top-most reservoir connection](https://github.com/OPM/opm-common/blob/76286d9b9768698d39f91544d50a0b199a64c99e/src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp#L178-L186).  In this particular case, however, the wells `WP3` and `WP4` don't actually intersect any active cells so there are no connections from which to derive the reference depth.

Running the model in parallel just generates an unfriendly diagnostic of the form
```
Error: Distributing properties to all processes failed
Internal error message: Well: WP4 - tried to access not initialized well reference depth

Error: Unrecoverable errors were encountered while loading input
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33574,1],4]
  Exit code:    1
--------------------------------------------------------------------------
```
The model **does** run in serial mode, but it does not generate any output because the output layer's well handling code unconditionally [asks for the reference depth](https://github.com/OPM/opm-common/blob/76286d9b9768698d39f91544d50a0b199a64c99e/src/opm/output/eclipse/AggregateWellData.cpp#L436) as part of forming the [`SWEL` array](https://github.com/OPM/opm-common/blob/76286d9b9768698d39f91544d50a0b199a64c99e/src/opm/output/eclipse/AggregateWellData.cpp#L673).  Instead we get diagnostic messages of the form
```
Starting time step 13, stepsize 284.937 days, at day 7020.06/7305, date = 22-Mar-2010
 Newton its= 2, linearizations= 3 (1.2sec), linear its=125 (3.7sec)
ERROR: Uncaught std::exception when running tasklet: Well: WP3 - tried to access not initialized well reference depth. Trying to continue.
```
I don't know how to properly handle this situation.  I also don't know how common this situation is.  This model is the first time I've seen it.

**Comment by blattms** [comment]
In parallel this must be a check in the serialization of the Schedule when distributing:
```
find . -name \*.[hc]pp| xargs grep -n "tried to access not initialized well reference depth"
./src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp:816:        throw std::logic_error(fmt::format("Well: {} - tried to access not initialized well reference depth", this->name()));
```

In serial this seems to happen when writing the output files. I would assume that those are broken.

**Comment by GitPaean** [comment]
>  In this particular case, however, the wells WP3 and WP4 don't actually intersect any active cells so there are no connections from which to derive the reference depth.

Do we know what commercial simulators do for this situation? If a well does not have any connections, nothing we can do about it. Then what we do with it becomes a design problem, I mean, what do we want.

**Comment by joakim-hove** [comment]
SInce this well does not have any connections I guess the correct way to handle it is just to ignore the well entirely in the simulator? 

Maybe just remove the throw [here](https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp#L824)

**Comment by OPMUSER** [comment]
Commercial simulator says:

` @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   1). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   2). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   3). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   4). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   5). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   6). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   7). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   8). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220   9). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      CONNECTS WITH A DEAD BLOCK                        
 @           (  70 220  10). THIS CONNECTION WILL BE IGNORED.                

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           NO FURTHER MESSAGES ABOUT                                       
 @           WELLS CONNECTING WITH DEAD BLOCKS                               
 @           WILL BE EMITTED.                                                

 @--MESSAGE  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           THE OUTPUT LIMIT FOR THESE MESSAGES                             
 @           CAN BE CHANGED WITH ITEM 13 OF THE                              
 @           MESSAGES KEYWORD OR WITH ITEM 220                               
 @           OF THE OPTIONS KEYWORD.                                         
   104 READING WCONINJE
   105 READING WCONPROD

 @--MESSAGE  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           OPENING WELL WP1      AT TIME   2922.00   DAYS                  
 @           CONTROLLED BY OIL RATE                                          

 @--MESSAGE  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           OPENING WELL WP2      AT TIME   2922.00   DAYS                  
 @           CONTROLLED BY OIL RATE                                          

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           CONNECTION DATA FOR WELL WP3      IS MISSING.                   
 @           THE CONNECTIONS MUST BE DEFINED USING KEYWORD COMPDAT           
 @           BEFORE THE WELL CONTROL KEYWORD (E.G. WCONPROD).                
 @           SHUTTING WELL.                                                  

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           CONNECTION DATA FOR WELL WP4      IS MISSING.                   
 @           THE CONNECTIONS MUST BE DEFINED USING KEYWORD COMPDAT           
 @           BEFORE THE WELL CONTROL KEYWORD (E.G. WCONPROD).                
 @           SHUTTING WELL.                                                  
   106 READING DATES   

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP3      HAS NO CONNECTIONS WITH THE GRID.                 
 @           SET THE CONNECTION DATA.                                        

 @--WARNING  AT TIME     2922.0   DAYS    ( 1-JAN-1999):
 @           WELL WP4      HAS NO CONNECTIONS WITH THE GRID.                 
 @           SET THE CONNECTION DATA.                                        
`

We should do the same so the user knows what is going on

**Comment by GitPaean** [comment]
@OPMUSER, thanks for the report. 

When coming to the output, does the commerical simulator report information about this well? If yes, what kind of bhp reference depth is it reporting?

**Comment by OPMUSER** [comment]
@GitPaean See the attached print file of the run.

[SMEAHEIA_21_GASSNOVA-R01.zip](https://github.com/OPM/opm-common/files/6383491/SMEAHEIA_21_GASSNOVA-R01.zip)

**Comment by OPMUSER** [comment]
@GitPaean I would prefer  `-1.E+20` to be consistent with commercial simulator, as using `NaN` implies we have an error of some sort.

**Comment by GitPaean** [comment]
>  I would prefer -1.E+20 

Okay. I will make a quick PR regarding to this.

**Comment by GitPaean** [comment]
It turns out to be harder to handle, considering the situations there is no `COMPDAT` input, there are `COMPDAT` inputs but there is no active connections, and connections can be filtered off after grid processing. 

I will come up with a solution later today or tomorrow.

**Comment by GitPaean** [comment]
It is another case to show that we should do the processing of the grid first before we parse many other keywords.

**Comment by GitPaean** [comment]
@OPMUSER , can you help to test this attached case to under this default bhp behavoir under `FIELD` unit?
[SPE1CASE2_MOD.DATA.gz](https://github.com/OPM/opm-common/files/6387789/SPE1CASE2_MOD.DATA.gz)

**Comment by OPMUSER** [comment]
@GitPaean not sure what you meant by "test this", so I used the commercial simulator and got this.

[SPE1CASE2_MOD_ECL.zip](https://github.com/OPM/opm-common/files/6388953/SPE1CASE2_MOD_ECL.zip)

I then tried tun OPM Flow using the nightly build but when I update the nightly builds I get this error

```
david@EIPC02-VirtualBox:~/OPM$ sudo python update_flow.py
Deleting old versions of flow
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libopm-common1' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libdune-common-dev libdune-geometry-dev libptscotch-6.0 libscotch-6.0 libtrilinos-zoltan12 pkg-config python-pyparsing
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing latest nightly version of flow
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libopm-simulators1
The following NEW packages will be installed:
  libopm-common1 libopm-grid1 libopm-simulators1 libopm-simulators1-bin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.8 MB of archives.
After this operation, 65.2 MB of additional disk space will be used.
Err:1 https://opm-project.org/package/nightly-bionic bionic/main amd64 libopm-common1 amd64 2021-03-09-git298e565-1~bionic
  404  Not Found [IP: 95.85.43.55 443]
Err:2 https://opm-project.org/package/nightly-bionic bionic/main amd64 libopm-grid1 amd64 2021-03-09-git750a7ed-1~bionic
  404  Not Found [IP: 95.85.43.55 443]
Err:3 https://opm-project.org/package/nightly-bionic bionic/main amd64 libopm-simulators1 amd64 2021-03-09-git3ec181e-1~bionic
  404  Not Found [IP: 95.85.43.55 443]
Err:4 https://opm-project.org/package/nightly-bionic bionic/main amd64 libopm-simulators1-bin amd64 2021-03-09-git3ec181e-1~bionic
  404  Not Found [IP: 95.85.43.55 443]
E: Failed to fetch https://opm-project.org/package/nightly-bionic/pool/main/o/opm-common/libopm-common1_2021-03-09-git298e565-1~bionic_amd64.deb  404  Not Found [IP: 95.85.43.55 443]
E: Failed to fetch https://opm-project.org/package/nightly-bionic/pool/main/o/opm-grid/libopm-grid1_2021-03-09-git750a7ed-1~bionic_amd64.deb  404  Not Found [IP: 95.85.43.55 443]
E: Failed to fetch https://opm-project.org/package/nightly-bionic/pool/main/o/opm-simulators/libopm-simulators1_2021-03-09-git3ec181e-1~bionic_amd64.deb  404  Not Found [IP: 95.85.43.55 443]
E: Failed to fetch https://opm-project.org/package/nightly-bionic/pool/main/o/opm-simulators/libopm-simulators1-bin_2021-03-09-git3ec181e-1~bionic_amd64.deb  404  Not Found [IP: 95.85.43.55 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Traceback (most recent call last):
  File "update_flow.py", line 36, in <module>
    update_flow(date_string)
  File "update_flow.py", line 21, in update_flow
    cmd("apt-get install -y libopm-common1 libopm-grid1 libopm-simulators1-bin")
  File "update_flow.py", line 11, in cmd
    subprocess.check_call( argv )
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'libopm-common1', 'libopm-grid1', 'libopm-simulators1-bin']' returned non-zero exit status 100
david@EIPC02-VirtualBox:~/OPM$ 
```
Joakim's python script use to work fine, so I don't think that is the problem, but this is outside my area of expertise.

**Comment by GitPaean** [comment]
> @GitPaean not sure what you meant by "test this", so I used the commercial simulator and got this.

Sorry @OPMUSER for the unclear request. I wanted you to test this with the commercial simulator to see the output related to uninitialized BHP reference depth under different unit system. It was mid-night and I did not write the message clearly enough, sorry for the confusion. 

```
                                                       WELL SPECIFICATION DATA
                                                       -----------------------

      -------------------------------------------------------------------------------------------------------------------------
      :   WELL   :   GROUP  : WELLHEAD :  B.H.REF : PREF- : DRAINAGE : GAS  : SHUT-IN : CROSS : PVT : WELL : FIP :    WELL    :
      :   NAME   :   NAME   : LOCATION :   DEPTH  : ERRED :  RADIUS  : INFL : INSTRCT : FLOW  : TAB : DENS : REG :  D-FACTOR  :
      :          :          : ( I, J ) :   FEET   : PHASE :   FEET   : EQUN :         : ABLTY :     : CALC :     :  DAY/MSCF  :
      -------------------------------------------------------------------------------------------------------------------------
      : PROD     : G1       :  10,  10 :-1.00E+20 :  OIL  : P.EQIV.R : STD  :   SHUT  :  YES  :  0  :  SEG :  0  :          0 :
      : INJ      : G1       :   1,   1 :-1.00E+20 :  GAS  : P.EQIV.R : STD  :   SHUT  :  YES  :  0  :  SEG :  0  :          0 :
      -------------------------------------------------------------------------------------------------------------------------
```

And @bska is correct, that the commercial simulator outputs `-1e+20` regardless of the unit system here.
