### ISSUE TITLE
Support for defaulted capillary pressure values

### ISSUE THREAD

**Issue by berland** [OPM/opm-common#2598]
The record
```
SWFN
0 0 1
0.5 0.5 1*  
1 1 0
/
```
gives [1, 0, 0] as values for capillary pressures when parsed with OPM, while the Eclipse manual states that defaulted pc-values should be linearly interpolated, warranting [1, 0.5, 0] as the correct deck interpretation.

**Comment by joakim-hove** [comment]
The interpolation happens in the table code "further up"

**Comment by berland** [comment]
Right. Is that interpolation code available through some Python API or will it  have to be reimplemented in `ecl2df`?

**Comment by berland** [comment]
A reimplentation is now present in https://github.com/equinor/ecl2df/pull/340

**Comment by bska** [comment]
@berland : Is this issue still relevant to you?

**Comment by berland** [comment]
No, the workaround in `ecl2df` works fine, this can be closed.

**Comment by bska** [comment]
>> Is this issue still relevant to you?
>
> No, the workaround in `ecl2df` works fine, this can be closed.

Thanks for quick response.  If we ever get a better API for this particular purpose we'll be sure to notify you.
