### ISSUE TITLE
2021-10-PRE: FSIP Should Not be in ALL Keyword

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#2672]
I may be wrong here but I don't think the FSIP vector (Field Salt In-Place) is associated with the ALL keyword in the SUMMARY section. Can we remove it to be consistent with the commercial simulator?

**Comment by joakim-hove** [comment]
I have taken your word for it: https://github.com/OPM/opm-common/pull/2676

**Comment by OPMUSER** [comment]
Fixed, so closing.
