### ISSUE TITLE
Issues with building opm-common

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#2703]
I just pulled master and tried to build opm-common but it fails. 

```
/home/thsa/workspace/opm/opm-common/src/opm/parser/eclipse/Parser/Parser.cpp: In member function ‘Opm::Deck Opm::Parser::parseFile(const string&, const Opm::ParseContext&, Opm::ErrorGuard&, const std::vector<Opm::Ecl::SectionType>&) const’:
/home/thsa/workspace/opm/opm-common/src/opm/parser/eclipse/Parser/Parser.cpp:1187:42: error: ‘relative’ is not a member of ‘Opm::filesystem’
             data_file = Opm::filesystem::relative( Opm::filesystem::canonical(dataFileName) );
```
Any clue? Jenkins seems to work.

**Comment by totto82** [comment]
Seems to be related to PR #2693

**Comment by bska** [comment]
What compiler (including version) do you use?

**Comment by akva2** [comment]
relative was not available in the ts. need to either use proximate or we have to do the same as i did in #2611

**Comment by joakim-hove** [comment]
OK - I'll look into it; would prefer the real relative but I fear that is quite involved.

**Comment by totto82** [comment]
`gcc 7.5.0, ubuntu 18.04`

**Comment by bska** [comment]
>> What compiler (including version) do you use?
>
> gcc 7.5.0, ubuntu 18.04

Okay, thanks&mdash;then we do at least know the direct cause of your build failure.  GCC 7.x does not support the full `std::filesystem` library, and in particular the `std::filesystem::relative()` function that [@akva2 mentions](https://github.com/OPM/opm-common/issues/2703#issuecomment-923841910).  The solution is either to import an implementation of `std::filesystem::relative()` from current libstdc++ sources or switch the code in #2693 to not use `relative()`.

**Comment by blattms** [comment]
>`gcc 7.5.0, ubuntu 18.04`
>

In that case (not upgrading to 20.04 in the near future) you should probably react
 to https://opm-project.org/pipermail/opm/2021-August/000757.html.
