### ISSUE TITLE
Cannot compile master cloned today

### ISSUE THREAD

**Issue by goncalvesmachadoc** [OPM/opm-common#2812]
When trying to compile flow in Ubuntu20  I get this error:
![image](https://user-images.githubusercontent.com/54812829/140309014-ccf662fc-f447-4475-88a6-78d61acc928e.png)
S.hpp is not a file in the repository. If commented out:
![image](https://user-images.githubusercontent.com/54812829/140309184-e97dd3bf-ef14-4d2a-b585-1391c7841ee2.png)

**Comment by akva2** [comment]
S.hpp is generated. somebody broke the rules and stuck the include of a generated header in a header.

**Comment by joakim-hove** [comment]
I'll come with a fix
