### ISSUE TITLE
2021-10 Warning Message Incorrect?

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#2847]
Currently if `NUPCOL` is less than six one gets this warning message:
```
Minimum NUPCOL value is 6 - see keyword MINNPCOL to adjust the minimum value
```
There is no `MINNPCOL` and it does not make sense to have  one from a user's prospective, but may be from a developer's. Suggest we change the message to:
```
Minimum NUPCOL recommended value is 6 - see keyword NUPCOL
```
or something similar.

**Comment by bska** [comment]
> There is no `MINNPCOL`

Actually there is, but it is an OPM-specific keyword that's used to enforce a minimum value for the `NUPCOL` parameter.  See [src/opm/parser/eclipse/share/keywords/900_OPM/M/MINNPCOL](https://github.com/OPM/opm-common/blob/df99685a92db717a2c38a32c59d964139485b86a/src/opm/parser/eclipse/share/keywords/900_OPM/M/MINNPCOL) for the definition of the keyword.  Whether or not it makes sense to have such a minimum threshold is of course a different matter.

**Comment by OPMUSER** [comment]
@bska I hear what you say, but this is really a developer option which we should "hide" from the user as it just begs questions; hence, the suggestion to change the message. 

Also I don't really want to document the keyword at this stage.

**Comment by OPMUSER** [comment]
MINNPCOL documented 10 2022-04 manual, so closing
