### ISSUE TITLE
Problem liking to DUNE-COMMON

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#287]
I am not able to build OPM after updating to current master

CMake is not able to find dune-common. 

```
CMake Error at /home/thsa/workspace/opm/opm-common/cmake/Modules/OpmPackage.cmake:85 (find_package):
  Could not find a package configuration file provided by "dune-common" with
  any of the following names:

    dune-commonConfig.cmake
    dune-common-config.cmake

```

I have tried to pass the dune-common path manually without success. 
A deep clean of everything did not help either. 
Any hint on what may have gone wrong?

**Comment by akva2** [comment]
see CMakeFiles/CMakeOutput.log and/or CMakeFiles/CMakeError.log for clues. in general it means you have no dune-common in your prefix paths.

**Comment by atgeirr** [comment]
I don't know exactly what you mean by passing the path manually, but I don't think DUNE_ROOT etc. works anymore (it was sort of old style cmake or something). What I do now is to install dune to a local dir (/path/to/duneinstall) and add that dir with cmake -DCMAKE_PREFIX_PATH=/path/to/duneinstall.

**Comment by totto82** [comment]
It worked when I build all the dune modules.

**Comment by totto82** [comment]
I meant installed!
