### ISSUE TITLE
ACTIONX: INCLUDE

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#2886]
Having an INCLUDE statement in an ACTIONX block is not allowed, so something like this:
```
ACTIONX
        ACT-01                                             /
        DAY  >= 1             AND                          /
        MNTH = FEB            AND                          /
        YEAR = 2021                                        /
/
--
--       LOAD INCLUDE FILE - WELSEGS, COMPSEGS and WSEGVALV
--
INCLUDE 
         '$WSEGVALV/prod1_msw_wsegvalv_data.inc'           /

ENDACTIO

```
Should be trapped, but currently we get this:
```
Processing dynamic information from
ACTIONX_WSEGVALV.DATA line 368
Initializing report step 0/24 at 2021-01-01 0 DAYS line 368
Processing keyword RPTRST at line 372
Processing keyword TUNING at line 378

Error: An error occurred while creating the reservoir schedule
Internal error: Item: I does not exist.

Error: Unrecoverable errors were encountered while loading input
Failed: 33713
```
Which would be difficult for a user to locate the cause of the error. Perhaps we should state that the INCLUDE statement is not allowed in an ACTIONX block.

**Comment by joakim-hove** [comment]
> Having an INCLUDE statement in an ACTIONX block is not allowed, so something like this:

Do you mean at it *should not* be allowed, or that it currently does not work in flow?

I have not thought about this before, but I actually think INCLUDE in ACTIONX should "work by accident". I don't know what the `prod1_msw_wsegvalv_data.inc` file looks like; but my hunch is that there is a problem with the contents of that file - not really related to ACTIONX. You could try:

1. Use an INCLUDE statement in ACTIONX to include a keyword which we are certain works - e.g. `WELOPEN`.
2. Inline the content of the  `prod1_msw_wsegvalv_data.inc` in the ACTIONX block and see how that works.

**Comment by OPMUSER** [comment]
Okay, to be clear, time stepping keywords, global keywords and the INCLUDE keywords are not allowed in the commercial simulator, as well as a few others. The issue is we should trap the error with a better message.

**Update**
The `prod1_msw_wsegvalv_data.inc ` contains the multi-segment keywords; however, placing the keywords inline gives the same error.  I think this is because there is an INCLUDE keyword right after the ENDACTIO keyword. 
```
ENDACTIO
-- ---------------------------------------------------------------------------------------------------------------------------------
-- WELL SPECIFICATIONS AND COMPLETIONS                                          
-- ---------------------------------------------------------------------------------------------------------------------------------      
--
--       LOAD INCLUDE FILE - WELLSPECS AND COMPATDAT
--
INCLUDE
         '$WSEGVALV/prod1_well_data.inc'                   /
--
--       WELL PRODUCTION WELL CONTROLS                                                     
--                                                                              
-- WELL  OPEN/  CNTL   OIL    WAT    GAS   LIQ    RES    BHP   THP   VFP    VFP  
-- NAME  SHUT   MODE   RATE   RATE   RATE  RATE   RATE   PRES  PRES  TABLE  ALFQ 
WCONPROD                                                                    
PROD1    SHUT   ORAT   300.0  1*     1*    1*     1*     60    2*              /
/
```

See the attached.

Note the data set runs without the ACTIONX implementation, as it based on the WSEGVALV test.

[ACTIONX_WSEGVALV.zip](https://github.com/OPM/opm-common/files/7675509/ACTIONX_WSEGVALV.zip)

**Comment by joakim-hove** [comment]
Can you send the file: `prod1_msw_wsegvalv_data.inc`

**Comment by OPMUSER** [comment]
You don't need it, the keywords are coded inline in the previously attached test.

But just in case, here are all the include files from WSEGVALV test case.

[include.zip](https://github.com/OPM/opm-common/files/7675666/include.zip)

**Comment by joakim-hove** [comment]
OK - should be fixed here: https://github.com/OPM/opm-common/pull/2887

**Comment by OPMUSER** [comment]
Okay, so that is a big plus I'll add a test for that as well and I'll update the manual accordingly.

**Comment by OPMUSER** [comment]
@joakim-hove 

Tusen takk.

Both the WSEGVALV and INCLUDE ACTIONX test now work with the fixes in the current master so closing issue.
