### ISSUE TITLE
[cmake] Either skip USE_* or adjust the defaults to the ones of DUNE's cmake buildsystem

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#2897]
This has cost me and some others (see OPM/opm-grid#561) quite some time for newer DUNE versions.

We have USE_MPI, USE_SUPERLU, USE_QUADMATH, that default to off. Being off will result in OPM not searching for these packages. As result none of the important targets are available in OPM. The problem is that DUNE will as default always search for them and use them. That means libraries might link to them and will use imported targets in the package configuration files. This will result in
cmake errors if the user has not manually chosen DUNE's default.

To fix this we should at least use DUNE's defaults or just get rid off these settings. This is not a problem, because:
- USE_MPI is off for historic reasons when some in the project thought that parallel computing was not useful. Luckily this changed. Let's change the default, too.
- SuperLU is also off for historic reasons to prefer UMFPack which gave better performance. This is not needed anymore as DUNE will prefer UMFPack if available in AMG
- QuadMath  is not used by us and we just stayed consistent and used off as default.

Note that the latter two are only an issue if someone has dune-fem on their system.

**Comment by alfbr** [comment]
The changes suggested may impact users, I suggest we move it to the mailing list.

**Comment by blattms** [comment]
Just found out that with the default USE_MPI=OFF we already fail for opm-common:
```
-- This build defaults to installing in /home/mblatt/opt/opm
CMake Error at opm-common/cmake/Modules/OpmSatellites.cmake:63 (add_executable):
  Target "test_cartgrid" links to target "MPI::MPI_C" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  opm-common/cmake/Modules/OpmLibMain.cmake:248 (opm_compile_satellites)
  CMakeLists.txt:119 (include)
```

**Comment by blattms** [comment]
This has been lingering for a quite a while with not so many reactions (same for the [mailing list](https://opm-project.org/pipermail/opm/2022-March/000787.html))

I quote my summary from the mailinglist here:

In my opinion this change will not have any impact on flow other than that everybody will
now build the parallel flow version and will not experience any kind of build issue with
DUNE >=2.8. The rest stays the same.

To me this clearly means less maintenance and better usability.

Errors like the one above are hard to judge for the average user (default USE_MPI=OFF) and rather annoying.

I really think that changing this for the release would make a lot of sense.

**Comment by blattms** [comment]
Nope. Even with the change SuperLU and Quadmath is not needed. The only change
is that we will search for it (like DUNE) and use it for linking (if needed).
