### ISSUE TITLE
Inconsistent Keyword Names in JSON Generator Input Files

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#2940]
Following #2936 I went looking for other instances of the same problem and I found the following

* [000_Eclipse100/A/APIVD](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/A/APIVD#L2)
* [000_Eclipse100/D/DEBUG](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/D/DEBUG#L2)
* [000_Eclipse100/L/LICENSES](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/L/LICENSES#L2)
*  [000_Eclipse100/R/RADFIN](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/R/RADFIN#L2)
* [000_Eclipse100/R/RSSSPEC](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/R/RSSSPEC#L2)
* [000_Eclipse100/S/SSWCR](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SSWCR#L2)
* [000_Eclipse100/S/SWF32D](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SWF32D#L2)
* [000_Eclipse100/T/TIGHTENP](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/T/TIGHTENP#L2)
* [000_Eclipse100/T/TPAMEPSS](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/T/TPAMEPSS#L2)
* [000_Eclipse100/V/DFLOWR](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/V/DFLOWR#L2)
* [000_Eclipse100/W/WSURFACT](https://github.com/OPM/opm-common/blob/8a0e1b21b982a82e74c950a65fa5e2493c70e54d/src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WSURFACT#L2)

As far as I can tell, most of these are copy-paste errors.  On the other hand, the commercial simulator does not have the keywords RSSSPEC (three 'S'-es) or DFLOWR, so those files are **probably** mistakes, especially since the former is identical to RSSPEC (two 'S'-es) and the latter is identical to VDFLOWR in the `000_Eclipse100/V` directory.

Looking more closely, our `RADFIN` description does not appear to have the right items.  My big concern is "DEBUG" however.  Did we really mean to create a keyword named "DEBUG_" with a trailing underscore?  I know we've discussed the "DEBUG" keyword on several occasions but I don't know if we've ever decided to support it even at the parser level.

Before I go on to create a PR to correct these input files, I'd like to know if the correct fix to "DEBUG" is to remove the trailing underscore or if to rename the file.  Any comments, @joakim-hove?

**Comment by joakim-hove** [comment]
> My big concern is "DEBUG" however. Did we really mean to create a keyword named "DEBUG_" with a trailing underscore?

I do not remember this, but do observe that keyword has a `deck_names = ["DEBUG"]` - i.e. we are creating a C++ class with the name `DEBUG_`; but it will recognize the deck keyword `DEBUG` without an underscore. My guess is that this was to avoid conflict with preprocesser symbol `DEBUG`?

**Comment by bska** [comment]
>> My big concern is "DEBUG" however. Did we really mean to create a keyword named "DEBUG_" with a trailing underscore?
>
> but do observe that keyword has a `deck_names = ["DEBUG"]` - i.e. we are creating a C++ class with the name `DEBUG_`; but it will recognize the deck keyword `DEBUG` without an underscore.

Ah, right.  I overlooked that bit.  Then I think "DEBUG" is modelled correctly and will take no action for that keyword.
