### ISSUE TITLE
MPI detection is inconsistent with DUNE's

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-common#296]
when I do not specify anything MPI related on my machine, the dune 2.5 build system detects and enables MPI but the OPM build system does not. note that this could be different with dune 2.4 or dune 2.6-rc1.

Also, the OPM build system does not seem to honor DUNE's ENABLE_$FOO mechanism, in particular the ENABLE_MPI flag.

**Comment by akva2** [comment]
the opm build system uses USE_XXX. mpi is off by default, pass -DUSE_MPI=1.

**Comment by andlaus** [comment]
yes, I know that if I explicitly specify this, both systems behave in a compatible manner. That said, the exaclty same thing may happen with other stuff so the whole story quickly becomes a nightmare.

**Comment by alfbr** [comment]
I have never set any MPI flag for dune, and have had no issues with it, so I am a bit uncertain what problem you are trying to solve. Unifying the name of the cmake variables for simplicity typically makes sense, but I am actually a bit uncertain in this particular case.

For OPM it still makes sense not to enable MPI by default, since you cannot even expect the MPI libraries you compiled against to be available on compute nodes. You should have a look at the battlefield that is MPI libraries on clusters. Not to mention the dependency of zoltan to get anything meaningful out of the MPI build. This is one very good example of where we need to hold off a bit more before doing the same as dune.

**Comment by andlaus** [comment]
> I have never set any MPI flag for dune, and have had  no issues with it, so I am a bit uncertain what problem you are trying  to solve.

I did not set it either and that is *exactly* the problem. I wanted to investigate the jenkins failure for OPM/opm-core#1192, cf. https://ci.opm-project.org/job/opm-core-PR-builder/80/ . Little annoyances like this eat a lot of (not only) my time and are completely [avoidable](https://github.com/OPM/opm-common/pull/295).

> For OPM it still makes sense not to enable MPI by default,

do you want to say that it does not make sense to make it work out of the box for most people?

> since you cannot even expect the MPI libraries you compiled against to be available on compute nodes-

well, if MPI is available and detected, it is reasonable to expect that it also gets enabled? The fact that sometimes MPI or zoltan is sometimes not properly installed has zero relevance here.

**Comment by andlaus** [comment]
(Note that -- unlike many others -- I can help myself with such issues, so I'm just the messanger.)

**Comment by alfbr** [comment]
> do you want to say that it does not make sense to make it work out of the box for most people?

Of course I do. The Red Hat packages do not have MPI still I believe, while the Debian and Ubuntu ones do. We did not get there by doing nothing, and I can assure you that I have spent a substantial amount of hours on it. We are slowly getting there, but we are not there today. It is just one example of our need for our own build system, sensible defaults in Dune may not be sensible for OPM.

> well, if MPI is available and detected, it is reasonable to expect that it also gets enabled? The fact that sometimes MPI or zoltan are not properly installed has zero relevance here.

Please try to understand. Build nodes and cluster nodes are two different beasts. Linking in MPI statically is a pita.

**Comment by andlaus** [comment]
> It is just one example of our need for our own build system, sensible defaults in Dune may not be sensible for OPM.

I'd argue that this issue and your arguments are actually points for the opposite.

> Please try to understand. Build nodes and cluster nodes are two different beasts. Linking in MPI statically is a pita.

I guess I'm fairly familiar with the situations on clusters because for years I had to beat my head on the desk because of one of them. nevertheless, I bet a bottle of wine that this issue does not influence the story on clusters at all. Wanna accept the bet?

**Comment by andlaus** [comment]
seems like this one is a WONTFIX. closing.
