### ISSUE TITLE
Deploy 3.10 Python wheels

### ISSUE THREAD

**Issue by anders-kiaer** [OPM/opm-common#2969]
Python 3.10 was released in October 🎉 (https://www.python.org/downloads/release/python-3100/)

Currently OPM only deploy wheels up to 3.9 (https://pypi.org/project/opm/#files).

Add 3.10 to deploy script?
https://github.com/OPM/opm-common/blob/d50b5852e076e01cdda8bbe53941f36696ed9607/python/generate-pypi-package.sh#L1-L50

**Comment by akva2** [comment]
last time i checked 3.10 was still not available in the docker image used to build.

**Comment by anders-kiaer** [comment]
Thanks for quick answer @akva2. Looks like all [`pypa` images currently contain 3.10](https://github.com/pypa/manylinux#image-content), but not sure when it was added.

**Comment by akva2** [comment]
indeed, it has been added now. PR opened. we don't provide pypy builds.
