### ISSUE TITLE
We need a better error message when we use `FIELD` in `WELSPECS`

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-common#2972]
With the following line, 

```
WELSPECS
   'WELL-1'      'FIELD'    5     5   800.0   'OIL'   2*  STOP   /
```

we are getting currently the following message, 
```
Program threw an exception: beginTimeStep() failed: _Map_base::at
```

The calling stack is 
```
__cxa_throw 0x00007fb55ff4f660
std::__throw_out_of_range(const char *) 0x00007fb55ff4637e
std::__detail::_Map_base::at hashtable_policy.h:769
std::unordered_map::at unordered_map.h:1006
Opm::ScheduleState::map_member::get ScheduleState.hpp:202
Opm::Schedule::getGroup Schedule.cpp:976
Opm::WellGroupHelpers::accumulateGroupEfficiencyFactor WellGroupHelpers.cpp:186
Opm::BlackoilWellModelGeneric::calculateEfficiencyFactors BlackoilWellModelGeneric.cpp:2157
Opm::BlackoilWellModel::beginTimeStep BlackoilWellModel_impl.hpp:277
Opm::EclProblem::beginTimeStep eclproblem.hh:1092
Opm::BlackoilModelEbos::prepareStep BlackoilModelEbos.hpp:267
Opm::NonlinearSolverEbos::step NonlinearSolverEbos.hpp:187
Opm::AdaptiveTimeSteppingEbos::step<…> AdaptiveTimeSteppingEbos.hpp:413
Opm::SimulatorFullyImplicitBlackoilEbos::runStep SimulatorFullyImplicitBlackoilEbos.hpp:260
Opm::SimulatorFullyImplicitBlackoilEbos::run SimulatorFullyImplicitBlackoilEbos.hpp:153
Opm::FlowMainEbos::runSimulatorRunCallback_ FlowMainEbos.hpp:554
Opm::FlowMainEbos::runSimulatorInitOrRun_ FlowMainEbos.hpp:624
Opm::FlowMainEbos::runSimulator FlowMainEbos.hpp:542
Opm::FlowMainEbos::execute_ FlowMainEbos.hpp:406
Opm::FlowMainEbos::execute FlowMainEbos.hpp:317
Opm::flowEbosOilWaterMain flow_ebos_oilwater.cpp:85
Opm::Main::runTwoPhase Main.hpp:596
Opm::Main::dispatchDynamic_ Main.hpp:294
Opm::Main::runDynamic Main.hpp:229
main flow.cpp:29
__libc_start_main 0x00007fb55fb6e0b3
_start 0x000055b93d19e3ce
```

**Comment by blattms** [comment]
Two questions
1. For average-markus developer, what field is missing and is this a problem in the deck? Hence what error message.
2. Is when running the simulator the best place for this error message or should rather be generated when or directly after reading the deck.

The surrounding code should catch std::out_of_range and generate the error message. Please be aware that at this stage in a parallel run, we might need to be really careful. Hence if it is possible to check this elsewhere that would be beneficial. On the other hand: Better with  a good error message than with the current bad one.

**Comment by bska** [comment]
>  is this a problem in the deck?

There's not enough information in the description to know for sure.  If the simulation model is intended to be compatible with ECLIPSE 100 then the well should not be parented directly to the `FIELD` group (i.e., `WELSPECS(2)` should **not** be `FIELD`).  On the other hand, ECLIPSE 300 does allow parenting a well directly to `FIELD`.

In any case the `FIELD` group should **always** exist, so while there may be an issue here, calling
```C++
Schedule::getGroup("FIELD", time)
```
should **always** succeed.  Please also report at least the key that generated this failure

**Comment by GitPaean** [comment]
Sorry for not providing more information. 

Basically, for keyword `WELSPECS`, `FIELD` is not allowed to use there. We should just throw and exit when parsing the deck. 

For the current error message and calling stacks, I did not investigate why it results in this unfortunate error. For the place that throws, the group name is "", and it could not find this group.

**Comment by bska** [comment]
>  for keyword `WELSPECS`, `FIELD` is not allowed to use there.

It **is** if the simulation model targets ECLIPSE 300.

**Comment by GitPaean** [comment]
``` c++
    const Group& Schedule::getGroup(const std::string& groupName, std::size_t timeStep) const {
        return this->snapshots[timeStep].groups.get(groupName);
    }
```

`groupName` here is `""`. Not sure why it results in this.

**Comment by bska** [comment]
> `groupName` here is `""`. Not sure why it results in this.

We don't have a group with no name.  That's the direct cause of the error.  How we got into the situation of looking up a group with no name is a different matter entirely.  Maybe the name of the parent group was defaulted which, in the context of an ECLIPSE 300 simulation model, means `FIELD`?

**Comment by GitPaean** [comment]
Modify the SPE1CASE1.DATA the following way can reproduce the problem. 

```
diff --git a/spe1/SPE1CASE1.DATA b/spe1/SPE1CASE1.DATA
index 076eb8d4..cfb4dadd 100644
--- a/spe1/SPE1CASE1.DATA
+++ b/spe1/SPE1CASE1.DATA
@@ -383,8 +383,8 @@ DRSDT
 
 WELSPECS
 -- Item #: 1    2      3       4       5        6
-       'PROD'  'G1'    10      10      8400    'OIL' /
-       'INJ'   'G1'    1       1       8335    'GAS' /
+       'PROD'  'FIELD' 10      10      8400    'OIL' /
+       'INJ'   'FIELD' 1       1       8335    'GAS' /
 /
```

**Comment by GitPaean** [comment]
> It is if the simulation model targets ECLIPSE 300.

It is an E100 deck, should we give the error message?

**Comment by bska** [comment]
> Modify the SPE1CASE1.DATA the following way can reproduce the problem.

Okay thanks.  Now I know why `groupName = ""` in this context.  When computing efficiency factors, class `BlackoilWellModelGeneric` will [call](https://github.com/OPM/opm-simulators/blob/a7e2b25627fb188330a0641b694e7184c207fb30/opm/simulators/wells/BlackoilWellModelGeneric.cpp#L2157) `WellGroupHelpers::accumulateGroupEfficiencyFactor()` to bring in group-level efficiency factors from the `GEFAC` keyword.  That function does not expect wells to be parented directly to `FIELD` and so [does not check](https://github.com/OPM/opm-simulators/blob/a7e2b25627fb188330a0641b694e7184c207fb30/opm/simulators/wells/WellGroupHelpers.cpp#L184-L187) for that condition.

In our case `FIELD`'s `parent()` is `""` and that's the direct cause of the failure.  It is arguably an error in `accumulateGroupEfficiencyFactors()` to not expect that someone might call the function directly on the `FIELD` group and we may well have other errors of the same kind in our codebase.

**Comment by bska** [comment]
Closing this as #2974 was merged.
