### ISSUE TITLE
Install python bindings by default as for opm-simulators

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#2976]
This inconsistency caused quite some confusion I guess it goes without saying that both should either install them or not for all modules.

I am proposing to install them. If this can be deactivated it needs to be for all modules with python stuff.

**Comment by alfbr** [comment]
Supported from our side. Thanks to the improvements on the build side, this should now work well for most.

**Comment by blattms** [comment]
Unless I here arguments against this, I will merge this tonight.

**Comment by blattms** [comment]
Obviously, I did not find the merge button for issues...

PR created.
