### ISSUE TITLE
Error when reading AQUCT keyword

### ISSUE THREAD

**Issue by rnyb** [OPM/opm-common#2985]
DATA file parser fails when reading AQUCT keyword

![image](https://user-images.githubusercontent.com/51825893/161700826-2073f227-1208-49e9-a300-ce3f0a4c35d6.png)

**Comment by totto82** [comment]
I think you need a / in the end
AQUCT
 1 2334 ..... /
/

**Comment by rnyb** [comment]
That did the trick, thanks. I totally overlooked that

**Comment by bska** [comment]
> I think you need a / in the end
> ```
> AQUCT
> 1 2334 ..... /
> /
> ```

Yes, that's right.  ECLIPSE does not require a terminating slash in this case, but OPM Flow does.  This issue has come up before, e.g., in #837, #1130, and #2255, but we've so far not decided to support the case of not terminating the analytic aquifer keywords.
