### ISSUE TITLE
OPM superLU detection seems to be incompatible with dune's

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-common#301]
this makes it much harder to use SuperLU as a linear solver than it needs to be: Using dune 2.5, I get

```
CMake Warning at /home/and/src/opm-grid/build-cmake/opm-grid-config.cmake:223 (message):
  Incompatible value "1" of variable "SUPERLU_MIN_VERSION_4_3"
Call Stack (most recent call first):
  /home/and/src/dune-common/cmake/modules/DuneMacros.cmake:175 (find_package)
  /home/and/src/dune-common/cmake/modules/DuneMacros.cmake:421 (find_dune_package)
  /home/and/src/dune-common/cmake/modules/DuneMacros.cmake:464 (dune_process_dependency_leafs)
  /home/and/src/dune-common/cmake/modules/DuneMacros.cmake:488 (dune_create_dependency_leafs)
  /home/and/src/dune-common/cmake/modules/DuneMacros.cmake:634 (dune_create_dependency_tree)
  CMakeLists.txt:25 (dune_project)
```

**Comment by andlaus** [comment]
(I guess I should stop reporting such issues now. there are quite a few left, if you feel bored, I'll report a few more.)

**Comment by akva2** [comment]
superlu is disabled by default in opm. pass -DUSE_SUPERLU=1 if you want to enable it.

**Comment by andlaus** [comment]
> superlu is disabled by default in opm.

yes, that's my point: it fails by default if you're unlucky enough to have the "wrong" system

**Comment by andlaus** [comment]
also: so far, everybody I've encountered so far happend to initially have a "wrong" setup.

**Comment by akva2** [comment]
the problem is the leakage of dune-istl config variables into opm, not the fact that opm disables superlu by default. that's the curse of template libraries.

it was disabled by default because dune 2.4 cannot handle the superlu version shipped with debian stretch.

**Comment by andlaus** [comment]
that may all well and true, but users who experience a failing build don't care.

**Comment by alfbr** [comment]
> that may all be well and true, but users who experience a failing build don't care.

SuperLU was disabled by default exactly to avoid failing builds for users. If we enable it again, anybody with SuperLu installed on Debian stable will get a failing OPM build.

**Comment by andlaus** [comment]
> SuperLU was disabled by default exactly to avoid failing builds for users.

well seems like that backfired. at least for people who use dune 2.5 or newer.

**Comment by blattms** [comment]
This is exactly does what it intends to. Warn people that different software might be configured in an incompatible way. I guess DUNE should do this too. It is not a bug it is a feature
