### ISSUE TITLE
Validation Re-Factoring Discussion

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3022]
This issue is being raised to discuss and seek feedback on the proposed Validation re-factoring, and hopefully agree on a way forward.

At the moment we have several "lists" that determine if a keyword is active, is available for ACTIONX processing, and a keyword item list (in a spreadsheet used to generate the validation code via a Python script for the keyword items). This is confusing and error prone, especially for new developers, on several occasions new keywords have been introduced and not working but their status as not been set to inactive. 

Here we propose to move all these "lists" by expanding the keyword JSON definitions, basically creating a JSON data base. The build system would then generate the required C++ lists and code using C++. This is proposed to be done in two phases, with Phase I replicating the _Unsupported keyword list_ and the _ACTIONX keyword list_.  Phase 2 would implement the Validation of the keyword items in the JSON files and the C++ code generator, that would actually perform the validation checking.  

So for example we could use something like this:
```json
{
"name": "ECLMC",
"sections": [
"RUNSPEC"
],
"active": 0
} 
```
To determine that the keyword is inactive, and a value of 1 meaning it is active and a value of 2 means that it active and works with ACTIONX keyword as well. I think for easy of use all JSON files should have this item to remind developers that they need to activate or inactivate the keyword.

For the keyword item validation, each item would have validation criteria based on allow_type and allow_msg. etc. So for example for the EHYSTR keyword we could have:
```json
{
"name": "EHYSTR",
"sections": [
"PROPS"
],
"active": 1,
"size": 1,
"items": [
{
"item": 1,
"name": "curvature_caplillary_pressure_hyst",
"value_type": "DOUBLE",
"default": 0.1,
"allow_act": "continue",
"allow_msg": "option is not supported - value ignored",
"allow_value": 0.1,
"allow_var": "HYSTRCP",
"comment": "Not used"
},
```
where:
```
"allow_act" = validation action stop or continue, 
"allow_msg" = the validation code message,
"allow_value" = the allowable value criteria, and
"allow_var" = the parameter name in the manual (this improves readability for the user).
```

The message format will be the same as before.
```
  EHYSTR: invalid value '1.100000' for item 1
  In file: Temp.data, line 340
  EHYSTR(HYSTRCP): option is not supported – value ignored
```
Naturally, the item validation parameters would only be entered if a validation was to performed, otherwise these parameters can be omitted.
 
The above is my first pass on how this would work, so open to discussion and changes.

**Comment by OPMUSER** [comment]
@bska I originally thought of doing this  using Python, but after discussing with @alfbr a "clearer" option would be just to expand the keyword generator instead. Unfortunately, somebody else would have to update that code, as my C++ skills are limited. However, I can update the JSON files, once we have agreed the format.

And yes I'm aware of that we have to have the > and < operators, etc., as well as lists.

**Comment by verveerpj** [comment]
As the initial developer of the new validation code, let me pitch in on the implementation details: I considered at the time using JSON files to convey the information, but somebody (probably Joakim?) convinced me that the information was so simple that it would be easier just to stick with a C++ structure. That turned out to be correct, the resulting structure is not very complex.

While developing it was found useful to use predicate functions or C++ lambda expressions within this structure. This allowed flexible expression of constraints on item values, without having to pre-define every possible constraint. This would be hard to reproduce in a JSON scheme, it would either limit the validation options, or still require adding some C++ code. Additionally, because of this, going this route would probably mean significant changes to the code generator (but I may be incorrect in this, I am not familiar with it.)

**Comment by OPMUSER** [comment]
I'm not one for flogging a dead horse as they say, but I just want to be clear on what is being proposed. 

Previously, the initial validation code used a spread sheet combined with a Python script to generated the C++ code to use the functions that @verveerpj  wrote. What I'm proposing is that we replace the spread sheet, since it has become STALE due to changes to the the actual validation code, with a JSON string, that combined with some additional C++, is used to generate the validation code based on the functions that @verveerpj  wrote. So for example:

```
"BRANPROP",
{
{5,{false, allow_values<std::string> {"NONE"}, "BRANPROP(ALQ-DEN): option is not supported and should be defaulted (1*)"}}, // ALQ_SURFACE_DENSITY 
},

```
Would be
```
{
  "name": "BRANPROP",
  "sections": [
    "SCHEDULE"
  ],
  "items": [
    {
      "name": "DOWNTREE_NODE",
      "value_type": "STRING"
    },
    {
      "name": "UPTREE_NODE",
      "value_type": "STRING"
    },
    {
      "name": "VFP_TABLE",
      "value_type": "INT"
    },
    {
      "name": "ALQ",
      "value_type": "DOUBLE",
      "default": 0
    },
    {
      "name": "ALQ_SURFACE_DENSITY",
      "value_type": "STRING",
      "default": "NONE",
      "allow_act": "continue",
      "allow_msg": "option is not supported and should be defaulted (1*)",
      "allow_value": "NONE",
      "allow_var": "ALQ-DEN",
    }
  ]
```
Another example for COMPORD:
```
{
     {2,{true, allow_values<std::string> {"DEPTH", "INPUT", "TRACK"}, "COMPORD(COMPORD): should equal DEPTH INPUT or TRACK – will STOP"}}, // ORDER_TYPE
  }
```
Would be:
```
{
  "name": "COMPORD",
  "sections": [
    "SCHEDULE"
  ],
  "items": [
    {
      "name": "WELL",
      "value_type": "STRING"
    },
    {
      "name": "ORDER_TYPE",
      "value_type": "STRING",
      "default": "TRACK"
      "allow_act": "stop",
      "allow_msg": "should equal DEPTH INPUT or TRACK",
      "allow_value": [ "DEPTH", "INPUT", "TRACK"],
      "allow_var": "COMPORD",    }
  ]
}
```
For integer and reals when the range of valid numbers are small then we would use the same approach. For  more complex  condition we would use the actual statement, so for example for EQUIL:
```

"EQUIL",
{
   {9,{true, [](int x) { return x >= -20 && x <= 0; }, "EQUIL(EQLOPT3): only values less than or equal to zero are supported (default is -5) - will STOP"}}, // OIP_INIT
   {10,{false, allow_values<int> {}, "EQUIL(EQLOPT4): compositional option not used – will continue"}}, // EQLOPT4
   {11,{false, allow_values<int> {}, "EQUIL(EQLOPT5): compositional option not used – will continue"}}, // EQLOPT5
},                        
```      
Would be:
```

{
  "name": "EQUIL",
  "sections": [
    "SOLUTION"
  ],
  "size": {
    "keyword": "EQLDIMS",
    "item": "NTEQUL"
  },
  "description": "The EQUIL item is used when equilibrating the model. The item should consist of exactly one record for each EQUIL region",
  "items": [
    {
     ....................................
    {
      "item": 9,
      "name": "OIP_INIT",
      "value_type": "INT",
      "default": -5,
      "comment": "Only values less than or equal to zero supported"
      "allow_act": "stop",
      "allow_msg": "only values less than or equal to zero are supported (default is -5)",
      "allow_value":  "{return x >= -20 && x <= 0; }",
      "allow_var": "COMPORD",    }
    },
    {
      "item": 10,
      "name": "EQLOPT04",
      "value_type": "INT",
      "comment": "This item is ECLIPSE300 specific"
      "allow_act": "continue",
      "allow_msg": "compositional option not used",
      "allow_value": "{}",
      "allow_var": "COMPORD",    }
    },
    {
      "item": 11,
      "name": "EQLOPT5",
      "value_type": "INT",
      "comment": "This item is ECLIPSE300 specific"
      "allow_act": "continue",
      "allow_msg": "compositional option not used",
      "allow_value": "{}",
      "allow_var": "COMPORD",    }
    }
  ]
}
```
Note that the actual syntax of `allow_value` is not fixed, and is open to discussion.

How will this be done? We could either extend the existing parser C++ code to include the above, or we could leave this as is and have a second pass that generates the validation code. I have no firm opinion on this, others are better qualified to comment.

What are the advantages of this refactoring:

1. All criteria for a keyword are in the one place, in the keyword's JSON definition, so it is easy to verify and amend.
2. Once implemented would increase consistency between the various validation lists.
3. Amending the criteria for current implementation means editing the raw C++ code, which is not a problem; however, the keyword items are split between strings, integers and reals, which means checking a keyword is cumbersome.
4. Will improve consistency between the validation code and the manual, as one only has to check in one place for a keyword. Checking C++ code to ensure the manual is consistent, is very time consuming and is thus seldom performed.

This is the last of my two cents.

**Comment by OPMUSER** [comment]
Closing as old.
