### ISSUE TITLE
opm-simulators does not pickup dunegrid, dunegeometry targets

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#305]
I am having build problems with the latest cmake changes. To me it seems like the target of dune-geometry and dune-grid are not picked up correctly. Hence either the wrong library in the system location is found or if there is none I get an error:
```
[ 98%] [100%] Building CXX object CMakeFiles/diagnose_relperm.dir/examples/diagnose_relperm.cpp.o
Building CXX object CMakeFiles/compute_tof.dir/examples/compute_tof.cpp.o
Building CXX object CMakeFiles/compute_tof_from_files.dir/examples/compute_tof_from_files.cpp.o
Building CXX object CMakeFiles/compute_initial_state.dir/examples/compute_initial_state.cpp.o
Linking CXX executable bin/compute_eikonal_from_files
/usr/bin/ld: cannot find -ldunegrid
/usr/bin/ld: cannot find -ldunegeometry
collect2: error: ld returned 1 exit status
```
For all opm-modules and dune-common the libraries are resolved by CMake to the full path. But for these to modules -ldunegrid -ldunegeometry is used.

**Comment by bska** [comment]
Just for the record, I'm seeing the same symptom (sibling build, Dune installed in a non-standard location provided through CMAKE_PREFIX_PATH).

**Comment by blattms** [comment]
Implicit dependencies are never search for. If I put dune-geometry and dune-grid into opm-core-prereqs.cmake they are searched for in opm-core otherwise not. Maybe <module>-prereqs.cmake needs to be included by <module>-config.cmake? Currently we only process those for the current module.

**Comment by akva2** [comment]
They are tranferred through the config file. No need to search again. I will look into why your setups break tmrw though i do not see why they are different from what has been tested :/

**Comment by bska** [comment]
> They are transferred through the config file

My `opm-grid-config.cmake` (either in the build tree or in the install tree) provides the list of opm-grid_LIBRARIES echoed below in addition to the opm-grid_LIBRARY build product created by the opm-grid module itself (with '`;`' replaced by newlines).

I notice that the installation location of the Dune libraries (`/home/bska/work/opm/inst/dune/2.4.1/dbg/seq`) is missing from the list.  Perhaps that's a clue?

---

```
"/data/projects/opm/inst/boost/1.63.0/lib/c++11/debug/libboost_date_time-gcc49-mt-d-1_63.so
/data/projects/opm/inst/boost/1.63.0/lib/c++11/debug/libboost_filesystem-gcc49-mt-d-1_63.so
dunegrid
dunegeometry
dunecommon
/usr/lib/libmpi_cxx.so
/usr/lib/libmpi.so
/usr/lib/x86_64-linux-gnu/libdl.so
/usr/lib/x86_64-linux-gnu/libhwloc.so
/usr/lib/x86_64-linux-gnu/libumfpack.so
/usr/lib/x86_64-linux-gnu/libamd.so
/usr/lib/liblapack.so
/usr/lib/libblas.so
/usr/lib/x86_64-linux-gnu/libm.so
/usr/lib/x86_64-linux-gnu/libsuitesparseconfig.a
-lrt
/data/projects/opm/build/opm/dbg/seq/dune-2.4.1/opm-common/lib/libopmcommon.a
/data/projects/opm/inst/boost/1.63.0/lib/c++11/debug/libboost_system-gcc49-mt-d-1_63.so
opmparser
opmjson
/home/bska/work/opm/inst/dbg/lib/x86_64-linux-gnu/libecl.so.2.3
/data/projects/opm/inst/boost/1.63.0/lib/c++11/debug/libboost_filesystem-gcc49-mt-d-1_63.a
/data/projects/opm/inst/boost/1.63.0/lib/c++11/debug/libboost_regex-gcc49-mt-d-1_63.a"
```

**Comment by blattms** [comment]
> They are transferred through the config file.

If you do not search them, you do not process their <module>-config files and therefore the imported CMake targets of the libraries are not defined. Which means we rely on the libraries and headers being installed under the same location of at least one direct dependency of the module.

If it worked for you then you are probably using system installed dune modules.
