### ISSUE TITLE
Missing output in RFT-file

### ISSUE THREAD

**Issue by tklov11** [OPM/opm-common#3108]
Hi,

I just noticed that I cannot find connection vectors (CONDEPTH, CONLENST, BRNST, BRNEN, CONSEGNO etc.) in the RFT-file from OPM for multisegment wells. Is this something you will provide in the future? Please let me know if you want me to send a full list of missing vectors.

Best regards
Trygve

**Comment by bska** [comment]
> I just noticed that I cannot find connection vectors (...) in the RFT-file from OPM for multisegment wells.

That's probably true.  Up until now, we've mostly treated the RFT file as an ugly duckling and we output essentially just enough data to support the `WRFT` keyword for regular (non-segmented) wells. To be honest I don't know what additional data items would be needed for multi-segmented wells, but I do know we're already missing some arrays needed to support the `WRFTPLT` keyword.

> Please let me know if you want me to send a full list of missing vectors.

Yes please.  Knowing which arrays are missing is necessary although probably not quite sufficient.  We also need to characterise the contents of those arrays if we want to provide reasonable and compatible result files.

**Comment by bska** [comment]
I'd like to give an update here.  We've added a series of PRs which collectively expand the set of vectors output to the RFT file and which introduce support for PLT and SEG data requested through the `WRFPLT` keyword.  While there are some missing pieces, I nevertheless believe that the following PRs are in a state that justify merging into the master branches.  I am going to start the review process now and then we'll hopefully get these in over the next fortnight or so.

OPM Common | OPM Simulators
--------------- | ------------------
#3151 | OPM/opm-simulators#4164
#3173 | OPM/opm-simulators#4180
#3184 |

**Comment by tklov11** [comment]
The introduced RFT file support for PLT and SEG data has been tested and result vectors have been compared and found to be in agreement with output from an alternative simulator. I therefore support starting the review process to incorporate these additions into the master branches.

**Comment by bska** [comment]
> I therefore support starting the review process to incorporate these additions into the master branches.

Thank you very much for testing this work.  I will start the review process now by marking #3151 as "ready for review".

**Comment by bska** [comment]
> > I therefore support starting the review process to incorporate these additions into the master branches.
> 
> Thank you very much for testing this work. I will start the review process now by marking #3151 as "ready for review".

I apologise for the delayed updates here.  I'm happy to report that every PR associated to this issue have been merged into the master branch now, and the feature is complete.  The final finishing touch is PR OPM/opm-simulators#4261 which ensures that we do not issue a misleading diagnostic message concerning segment data in `WRFTPLT`.

**Comment by blattms** [comment]
I guess we can close this then?

**Comment by OPMUSER** [comment]
Closing as completed.
