### ISSUE TITLE
Compile error: Boost_UNIT_TEST_FRAMEWORK_LIBRARY

### ISSUE THREAD

**Issue by ajikmr** [OPM/opm-common#3147]
Hello,

Recently I got error when installing opm-common on ubuntu20.04. This issue was not there previously.

*******************
```
CMake Error in /home/***/opm-common/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "Boost::unit_test_framework" includes non-existent path
    "/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not  provide.

CMake Error at /usr/share/cmake-3.16/Modules/CheckCXXSourceCompiles.cmake:110 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  cmake/Modules/UseDynamicBoost.cmake:19 (check_cxx_source_compiles)
  cmake/Modules/OpmLibMain.cmake:96 (include)
  CMakeLists.txt:259 (include)

-- Configuring incomplete, errors occurred!
See also "/home/***/opm-common/build/CMakeFiles/CMakeOutput.log"
```
*************************

I already had relevant boost libraries installed on system.
*****************
libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libboost-dev is already the newest version (1.71.0.0ubuntu2).
libboost-test-dev is already the newest version (1.71.0.0ubuntu2).
*******************

To fix the problem, I had to comment out line 87 of [`opm-common/cmake/Modules/OpmLibMain.cmake`](https://github.com/OPM/opm-common/blob/ff3da8cc79507fc788866ca6182ada7d8aa3a37a/cmake/Modules/OpmLibMain.cmake#L85-L87) file. 
```cmake
list (REMOVE_ITEM "${project}_LIBRARIES" "${Boost_UNIT_TEST_FRAMEWORK_LIBRARY}")
```
Please see if we can handle this issue in a better way. 

Thanks,
Ajit.

**Comment by bska** [comment]
Thank you for the report.  This appears build-system related.  Is there anything that jumps out at you, @akva2 or @blattms?

**Comment by akva2** [comment]
the cmake config file for boost-unit-test-framework is broken if they include /include in their INTERFACE_INCLUDE_DIRECTORIES. and that file is beyond our control. 

looking at that file, it does
```cmake
get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../../include/" ABSOLUTE)
get_filename_component(_BOOST_LIBDIR "${_BOOST_CMAKEDIR}/../" ABSOLUTE)

# Create imported target Boost::unit_test_framework
add_library(Boost::unit_test_framework UNKNOWN IMPORTED)

set_target_properties(Boost::unit_test_framework PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)
```

which should be fine. this makes me suspect a local system issue. do you have some random boost_unit_test_framework-config.cmake on your system?

**Comment by ajikmr** [comment]
Thank you for your comments. I launched a fresh vm and there is no error. 

So, the earlier error must be some random boost library as you guessed. I think it is from one of the conda installations I have. 

Thanks again for looking into the problem.
Regards,
Ajit
