### ISSUE TITLE
2022-04 and Master: PDEW and PBUB Issue

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3159]
There is a restart file error on writing out the PDEW and PBUB arrays, as the data seems to be scaled by around10,000; notice the x-axis values in the figure below, that compares OPM Flow with the commercial simulator. 

![image](https://user-images.githubusercontent.com/17958927/192448301-9a103fa5-44f1-4c4e-8882-fdc3866398db.png)

See the discussion: https://github.com/OPM/ResInsight/issues/9316

**Comment by totto82** [comment]
It is given as  `  {"PBUB",     UnitSystem::measure::identity,  data::TargetType::RESTART_AUXILIARY,     bubblePointPressure_},`
in the code. i.e. it outputs in si-units

**Comment by OPMUSER** [comment]
But the output should be bars not PA.

**Comment by OPMUSER** [comment]
Will this fix it?

`{"PBUB",     UnitSystem::measure::pressure,  data::TargetType::RESTART_AUXILIARY,     bubblePointPressure_}, `

If so I can submit a PR if you like.

**Comment by totto82** [comment]
Yes and similarly for PDEW

**Comment by bska** [comment]
@OPMUSER: We merged OPM/opm-simulators#4133.  Is this issue still present?  If not, please close it.

**Comment by OPMUSER** [comment]
I checked before I submitted the PR, all is good.
![image](https://user-images.githubusercontent.com/17958927/192512426-bc0bc56c-c98a-49d1-b98a-ff914d5f2ff8.png)

So closing.

**Comment by bska** [comment]
> checked before I submitted the PR, all is good.

Wonderful, I'm happy to hear that.  Thanks a lot for the quick turnaround.

**Comment by OPMUSER** [comment]
Could not have done it without @totto82 pointing me in the right direction.
