### ISSUE TITLE
2022-04: Bug in COMPDATA(DIRECT)

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3164]
If COMPDAT(DIRECT) is entered as lowercase instead of uppercase, I get my favorite message again:
```
OPM Flow Process 14340 Segmentation Fault - Job Aborted
```
E100 runs the model without issue.

Note we flag the issue with:
```
Error: Problem with keyword COMPDAT
In SIM_PEE_Basic_Simulator.DATA line 602.
Internal error: Unsupported completion direction y
```
But we should just convert to uppercase first before checking.

It would be good to get a fix for this in time for the 2022-10 release. If you point me in the right direction, I'll give it a go.

**Comment by bska** [comment]
The easiest approach here is **probably** to amend [`Connection::DirectionFromString()`](https://github.com/OPM/opm-common/blob/77676000f7f717d4b962a19b743fc48972775980/src/opm/input/eclipse/Schedule/Well/Connection.cpp#L386-L399) to recognise both upper and lower case direction descriptors.
