### ISSUE TITLE
2022-10-RC1: WRFTPLT Issues

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3211]
If the WRFTPLT keyword is entered before the wells have been declared, that is before WELSPECS, 
```
--
--       WELL RFT, PLT AND SEGMENT DATA 
--
-- WELL  RFT   PLT   SEGMENT
-- NAME  DATA  DATA  DATA
WRFTPLT
'*'      RPT   1*    1*                /
/

WELSPECS
     'INJE01' 'I'    1  1 1* 'WATER'     /
     'PROD01' 'P'    10 10  1*  'OIL'   7*  /
/
```
then we get the following error messages:
```
Error: Problem with keyword WRFTPLT
In WRFTPLT-00.DATA line 2358
No wells/groups match the pattern: '*'

Error: Unrecoverable errors while loading input: Problem with keyword WRFTPLT
In WRFTPLT-00.DATA line 2358
No wells/groups match the pattern: '*'
```
Secondly,
```
--
--       WELL RFT, PLT AND SEGMENT DATA
--
-- WELL  RFT   PLT   SEGMENT
-- NAME  DATA  DATA  DATA
WRFTPLT
'*'      1*    REPT  1*                /
/
```
Results in no PLT data being written out, but the manual states that WRFTPLT(PLT) is supported. Is the manual incorrect?

Also, the WRFTPLT(MULTSEG) option has no output as well, and the manual says it is not supported - is this correct?

There have been many PRs on this topic, so it is a bit confusing, appreciate some clarification.

**Comment by bska** [comment]
We follow the commercial simulator's lead here and apply the `WRFTPLT` keyword only to wells which have already been defined in `WELSPECS`.  In other words using `WRFTPLT` before `WELSPECS` is supposed to be an error or at least not generate any output.  We could probably issue a better diagnostic and continue, though.

> Secondly,
> ```
> --       WELL RFT, PLT AND SEGMENT DATA
> --
> -- WELL  RFT   PLT   SEGMENT
> -- NAME  DATA  DATA  DATA
> WRFTPLT
> '*'      1*    REPT  1*                /
> /
> ```
> Results in no PLT data being written out, but the manual states that WRFTPLT(PLT) is supported. Is the manual incorrect?

If the manual states that we output PLT data then the manual is, indeed, incorrect here.  As of right now, in the master sources and in what will become the 2022.10 release, we parse the keyword correctly but we then treat `WRFTPLT` as an alias for the more basic `WRFT` keyword&mdash;albeit with slightly different behaviour for open vs. closed wells&mdash;meaning we only ever print the basic RFT information even if `WRFTPLT` asks for `PLT` or `SEG` information.

That said, work is ongoing (#3151, #3173, #3184, and others) to expand the set of supported vectors in Flow's implementation of the `WRFTPLT` keyword.  I expect that this work will start to become available in master once the release is out.  This, on the other hand, means we won't get it in a public release until 2023.04 at the earliest.

> WRFTPLT(MULTSEG) option has no output as well, and the manual says it is not supported - is this correct?

Yes, that is correct.

> There have been many PRs on this topic, so it is a bit confusing, appreciate some clarification.

None of the recent PRs have been merged yet, but testing is going on behind the scenes and the initial results are promising.

**Comment by OPMUSER** [comment]
@bska  Noted with thanks.

Closing as comments addressed.
