### ISSUE TITLE
Path for libecl library not correctly set when linking flow

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#337]
~Took me some time to figure this out. Default build type for libecl seems to be RELWITHDEBINFO while the
genuine opm modules use RELEASE. This means that if I do not set the build type manually, I run into the
following troubles:~ 

After updating all my modules, I cannot run not-installed flow anymore as libecl is not found.
```
$ ldd bin/flow| grep ecl
	libecl.so.2 => not found
```
I build all my modules in module-name/opm-parallel Using `cmake -C ../../opts.cmake ..`. Same for libecl (libecl/parallel).
```
$ cat ../../opts.cmake| grep -v -e "^#"
set(USE_MPI ON         CACHE STRING "Use mpi")
set(BUILD_TESTING OFF CACHE BOOL "Build tests")
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY 1 CACHE BOOL "" FORCE)
set(BUILD_ECL_SUMMARY ON CACHE BOOL "Build summary.x")
set(BUILD_APPLICATIONS OFF CACHE BOOL "Build applications")
```

The resean is there is no imported target for build type RELEASE in libecl. 
```
$ grep -B5 libecl.so ../..libecl/opm-parallel/eclConfig.cmake
)

# Import target "ecl" for configuration "RelWithDebInfo"
set_property(TARGET ecl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ecl PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/mblatt/src/dune/opm-2.6/libecl/opm-parallel/lib/libecl.so.2.3"
  IMPORTED_SONAME_RELWITHDEBINFO "libecl.so.2"
```
but we are using this one for opm-simulators:
```
$ grep BUILD_TYPE CMakeCache.txt 
CMAKE_BUILD_TYPE:STRING=Release
```

Edit: Turns out I have the same problem when explicitly setting CMAKE_BUILD_TYPE=Release. Therefore this seems to be not related to the build type.

**Comment by blattms** [comment]
Why on earth this did not bite me before is beyond me.

**Comment by blattms** [comment]
This seems to be not related to the build type used. See edited description

**Comment by akva2** [comment]
i noticed the same thing yesterday. i'm in middle of things but try this:
in OpmFind.cmake, there's an if (TARGET ecl) block. 

replace the
```cmake
set(ecl_LIBRARIES ...)
```
with
```cmake
set(ecl_LIBRARIES ecl)
```
then it links using target which should resolve the issue.

**Comment by blattms** [comment]
Workaround works.

**Comment by akva2** [comment]
then please pr
