### ISSUE TITLE
Long compile time with g++-12

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#3401]
Somehow compilation time skyrocketed (e.g. on Debian) with the move to g++12. Especially the ParserInit.cpp et al files take forever (4 times slower) and consumes up to 2 GB.

I have already started the process of refactoring (Not including all generated headers there but splitting ParserInit into multiple files ParserInitA, ..., there is another candidate). Let's see how far that gets us. But this is low priority for now.

Workaround would be to use ccache to compile these not to often.

**Comment by bska** [comment]
> Especially the ParserInit.cpp et al files take forever (4 times slower) and consumes up to 2 GB.

Release?  Debug?  Both?

**Comment by blattms** [comment]
I am impatient and just jump to the conclusion after watching cc1plus for 11 minutes: Both!

Maybe it is the warnings that we activate. These headers have myriads of structs in them (including A-Z.hpp).

**Comment by blattms** [comment]
> Maybe it is the warnings that we activate.

Which are rather hard to deactivate as they are always set if there no -W* option set in the compile flags by the user. Is there a `-Wnone` or similar? :rofl:

**Comment by blattms** [comment]
I'll try -Wdata-time, and get rid of those... :laughing:

**Comment by akva2** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html (see -w)
