### ISSUE TITLE
Compilation failure using 'WITH_NDEBUG ON'

### ISSUE THREAD

**Issue by vkip** [OPM/opm-common#3443]
https://github.com/OPM/opm-common/pull/3431 causes compilation to fail if one of the CMAKE_*LANGUAGE*_FLAGS* variables is empty (error message ~ 'REPLACE expects at least four arguments..'  [cmake 3.24.3]).  In my setup the Fortran variables are typically empty.

**Comment by bska** [comment]
@akva2 : Would you mind looking into this, please?
