### ISSUE TITLE
Embedded libfmt cannot be used

### ISSUE THREAD

**Issue by akva2** [OPM/opm-common#3495]
Building with embedded libfmt will cause an exception to be thrown in flow,
> ```
> Program threw an exception: invalid type specifier
> ```
when running the Norne case (and likely for most others).

**Comment by bska** [comment]
> Building with embedded libfmt will cause an exception to be thrown in flow,

There must be more to it than that.  I'm using our embedded libfmt package on Ubuntu 20.04 LTS, GCC 9.3, Boost 1.71, CMake 3.16 and I'm running the standard Norne case (`NORNE_ATW2013`) from OPM-Tests without issue.

**Comment by bska** [comment]
That said, I'm absolutely not opposed to upgrading our bundled copy of libfmt if that's what it takes to fix your issue.

**Comment by akva2** [comment]
hmm, okay. i must admit i didn't investigate the details too much. updating the embedded would definitely take care of it, the rc2 packages are confirmed working.

**Comment by akva2** [comment]
nope
