### ISSUE TITLE
Python opm 2023.04 appears to lack boost169

### ISSUE THREAD

**Issue by mferrera** [OPM/opm-common#3519]
-  *OS*: 22.04.2 LTS
- *Python*: Python 3.8.10

## Steps to reproduce
```shell
python -m venv opm
pip install -U pip opm
pip list
# Package       Version
# ------------- -------
# opm           2023.4
# pip           23.1.2
# pkg_resources 0.0.0
# setuptools    44.0.0
python -c "from opm._common import action"
```

Results in

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../test/opm/lib/python3.8/site-packages/opm/_common.py", line 12, in <module>
    from .opmcommon_python import action
ImportError: libboost_system.so.1.69.0: cannot open shared object file: No such file or directory
```
But
```shell
pip install opm==2022.10
pip list
# Package       Version
# ------------- -------
# opm           2022.10
# pip           23.1.2
# pkg_resources 0.0.0
# setuptools    44.0.0
python -c "from opm._common import action"
# No error
```
Also,
```shell
opm-2022.10-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.1 MB)
opm-2023.4-cp38-cp38-manylinux2014_x86_64.whl (4.3 MB)
```
There is a fairly large size difference :-)

cf. https://github.com/OPM/opm-common/commit/6316768bbb9ac44eb7eac283697708a114ba651b ?

**Comment by akva2** [comment]
Not that one but building using cmake. I will have to fiddle some flags to make it use static boost, I completely overlooked that. Will fix.
________________________________
From: mferrera ***@***.***>
Sent: Thursday, May 11, 2023 4:58:54 PM
To: OPM/opm-common ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OPM/opm-common] Python opm 2023.04 appears to lack boost169 (Issue #3519)


  *   OS: 22.04.2 LTS
  *   Python: Python 3.8.10

Steps to reproduce

python -m venv opm
pip install -U pip opm
pip list
# Package       Version
# ------------- -------
# opm           2023.4
# pip           23.1.2
# pkg_resources 0.0.0
# setuptools    44.0.0
python -c "from opm._common import action"

Results in

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../test/opm/lib/python3.8/site-packages/opm/_common.py", line 12, in <module>
    from .opmcommon_python import action
ImportError: libboost_system.so.1.69.0: cannot open shared object file: No such file or directory

But

pip install opm==2022.10
pip list
# Package       Version
# ------------- -------
# opm           2022.10
# pip           23.1.2
# pkg_resources 0.0.0
# setuptools    44.0.0
python -c "from opm._common import action"
# No error

Also,

opm-2022.10-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.1 MB)
opm-2023.4-cp38-cp38-manylinux2014_x86_64.whl (4.3 MB)

There is a fairly large size difference :-)

cf. 6316768<https://github.com/OPM/opm-common/commit/6316768bbb9ac44eb7eac283697708a114ba651b> ?

**Comment by akva2** [comment]
I have pushed out 2023.4.1 that should fix this. Please confirm.

**Comment by mferrera** [comment]
LGTM, thanks for the quick resolution!
