### ISSUE TITLE
Error message for missing grid keywords

### ISSUE THREAD

**Issue by goncalvesmachadoc** [OPM/opm-common#3551]
If a grid defining keyword (TOPS in this example) is omitted, this message is given:
![image](https://github.com/OPM/opm-common/assets/54812829/6fd247fa-042c-45c9-b309-a504e0bf5c16)
It would be nice for the user to know the specific keyword missing.

**Comment by verveerpj** [comment]
Looking at the code that seems actually a bit complicated. It seems that it checks for several types of grids defined by various combinations of keywords. If none is found, this generic error is shown.

This is the code in question: https://github.com/verveerpj/opm-common/blob/d036f6aaaa76d54efa75ea81db8594536cf61c1c/src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp#L337-L351

To make it more specific one would have to guess which grid type the user intended and then look what was missing. That should be possible, but it might also be that it is ambiguous what the user wanted. In that case all the possible cases, with missing keywords could be listed in the error message. 

I am seeing this correctly?

**Comment by atgeirr** [comment]
> I am seeing this correctly?

I think so.

The easiest way to give good feedback would be to add to the error message something like "For grid creation you either need COORDS and ZCORN, or alternatively DX, DY, DZ and TOPS" (don't use this verbatim without checking, I am not sure I remember things correctly) , without trying at this point to guess which the user wanted.

**Comment by verveerpj** [comment]
> > I am seeing this correctly?
> 
> I think so.
> 
> The easiest way to give good feedback would be to add to the error message something like "For grid creation you either need COORDS and ZCORN, or alternatively DX, DY, DZ and TOPS" (don't use this verbatim without checking, I am not sure I remember things correctly) , without trying at this point to guess which the user wanted.

That seems reasonable, it may need a few more options, since there are also other options, e.g. RADIAL, but those could also b e listed, assuming it is ok if the error message gets a bit larger.

**Comment by atgeirr** [comment]
> it may need a few more options

Sure, that is why I made it clear that my suggestion was only a sketch! One could also add a reference to the relevenant chapter of the manual, but that might be a little fragile?

**Comment by bska** [comment]
If we're really determined to give good diagnostic messages here, I think we should split this `if`-`else` chain into two separate stages;

1. Identify which grid type keywords exist:
   1. Cartesian&mdash;some combination of `DX`, `DY`, `DZ`, `DXV`, `DYV`, `DZV`, `TOPS`, `DEPTHZ`
   2. Corner-point (`COORD` and `ZCORN`)
   3. Spider
   4. Cylinder
2. Check that there's only a single grid type, otherwise issue a diagnostic and abort
3. Construct that grid type, and issue a diagnostic/abort if the keyword combination is inconsistent&mdash;e.g., missing `TOPS` for the (`DX`, `DY`, `DZ`, `TOPS`) specification.

**Comment by totto82** [comment]
Just a side note if this part is planned to refactored. Currently the check will fail if DX ++ is given by EQUILS and not directly as keywords.
