### ISSUE TITLE
Is it Okay to Rely on Schedule::getWells(timeStep) Returning Wells in Order of Appearance?

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#357]
Right now, as a consequence of using an [`Opm::OrderedMap<>`](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp) to manage the wells in a simulation model, the code fragment below will iterate over the wells in the order they are declared in the `WELSPECS` keyword (possibly entered multiple times in a simulation deck).

Is it okay to rely on this fact/implementation detail?  The reason I ask is that restart data for wells must be output in the order of the wells' appearance/declaration.

---

```C++
// timeStep is integer step ID (std::size_t)
for (const auto& wellPtr : schedule.getWells(timeStep)) {
    use(*wellPtr);
}
```

**Comment by joakim-hove** [comment]
> Is it okay to rely on this fact/implementation detail?

Yes - to provide that promise is the sole reason the class exists; there is a test of the class - which is admittedly not very extensive: https://github.com/OPM/opm-common/blob/master/tests/parser/OrderedMapTests.cpp

An interesting question where the distinction between implementation detail and API goes? In situations like this the test becomes "part of the API (contract)" - which is of course not ideal.

**Comment by bska** [comment]
> to provide that promise [order of appearance iteration] is the sole reason the class exists;

Thanks.  Sorry for not looking into the history of the class.  Its purpose is clearly stated in the first commit, 4c477b6.
