### ISSUE TITLE
Completion::fromCOMPDAT(): Possible Bug?

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#359]
I was reading through [`Completion.cpp`](https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/Schedule/Completion.cpp) and came across this line from [`Completion::fromCOMPDAT(grid, prop, kw, wells)`](https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/Schedule/Completion.cpp#L215):
```C++
if( prev_compls[ index ] == 0 ) (*well)->getCompletions().size();
```
This looks a bit strange to me. Does the `getCompletions()` member function&mdash;or the act of invoking `.size()` on its return value&mdash;have some non-local effect?  If not, why do we not do something to the result of `.size()`?

**Comment by joakim-hove** [comment]
I can only agree it looks weird, can look more into it on Monday.

**Comment by bska** [comment]
> can look more into it on Monday.

:+1: 

Thanks Joakim!

**Comment by lars-petter-hauge** [comment]
Got into this part of the code when working with https://github.com/OPM/opm-common/pull/387

It is indeed a bug and patch will be added to the PR.

**Comment by bska** [comment]
This is no longer relevant.  The code in question was rewritten long ago.
