### ISSUE TITLE
flow supresses obvious well misconfigurations

### ISSUE THREAD

**Issue by lars-petter-hauge** [OPM/opm-common#361]
Flow does not warn on well misconfigurations. Can be reproduced in SPE1 dataset by changing the wellname within COMPDAT, WELSPECS and WCONPROD/WCONINJE e.g.:

>
```
WELSPECS
  'PROD' 'G1'  10 10 8400 'OIL' /
/
COMPDAT
  'PROD2' 10 10 3 3 'OPEN' 1* 1* 0.5 /
/
WCONPROD
  'SOMETHINGELSE' 'OPEN' 'ORAT' 20000 4* 1000 /
/
```
will run without warnings, although no well will be present in the result.

Found the issue while working on a different topic. Haven't looked into it much.

**Comment by joakim-hove** [comment]
Regarding `WCONPROD`, can you try `'WX*' `, i.e. a wildcard with no matches in Eclipse?

**Comment by lars-petter-hauge** [comment]
Didn't seem to change the result in any way

**Comment by joakim-hove** [comment]
You get an error from Eclipse in that case?

**Comment by lars-petter-hauge** [comment]
yepp:

 

> @--  ERROR  AT TIME        0.0   DAYS    ( 1-JAN-2015):
>  @           NO WELLS MATCH THE NAME WX*                                     
>  @           IN THE WELL CONTROL DATA KEYWORD WCONPROD.                      
>     63 READING WCONINJE
> 
>  @--MESSAGE  AT TIME        0.0   DAYS    ( 1-JAN-2015):
>  @           OPENING WELL INJ      AT TIME      0.00   DAYS                  
>  @           CONTROLLED BY GAS RATE                                          
>     64 READING TSTEP   
> 
>  @--  ERROR  AT TIME        0.0   DAYS    ( 1-JAN-2015):
>  @           THE CONTROL DATA FOR WELL PROD                                  
>  @           HAS NOT BEEN DEFINED.

**Comment by joakim-hove** [comment]
> yepp:

Very good; then I just suggest we add a new `ParseContext` error mode like e.g. `SCHEDULE_INVALID_WELLS` and we just require that the `Schedule::getWells( well_pattern )` method returns *at least* one well.

**Comment by atgeirr** [comment]
> require that the Schedule::getWells( well_pattern ) method returns at least one well

Require this from the calling site or in the method? I think calling site is probably more flexible.
