### ISSUE TITLE
Potential Problem in MULTREGTScanner

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#3627]
Commit d53d8b4947 (PR #1240) **may** have introduced a mistake in the processing of keyword `MULTREGT`.  In particular, the definitions of `j1` and `j2` changed from
```C++
j1 = globalIndex1 / region.getNX() % region.getNY();
j2 = globalIndex2 / region.getNX() % region.getNY();
```
to their [current definitions](https://github.com/OPM/opm-common/blob/f95cbea9211bec2479b01ccb87cf92dc41d6bf29/src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp#L277-L278) of
```C++
j1 = globalIndex1 / this->nx % this->nz;
j2 = globalIndex2 / this->nx % this->nz;
```
Replacing `getNY()` with `this->nz` in this particular calculation looks very suspicious to me, but we've run with this version for more than 3 and a half years without noticing any real problems&ndash;even for [Norne](https://github.com/OPM/opm-tests/blob/8ccc153d37386c20e54418df69eb4a0adc3955d9/norne/INCLUDE/PETRO/MULTREGT_D_27.prop#L45)&ndash;so maybe I'm missing something.

**Comment by blattms** [comment]
Actually, I don't see any relation of the global index of cell with extent of one region that would justify the previous version. To me the change looks like a bugfix.

We take the global index and compute i and j to determine whether the connection between the two cells is an NNC or not below.

**Comment by bska** [comment]
> Actually, I don't see any relation of the global index of a cell with the extent of one region that would justify the previous version. To me the change looks like a bugfix.

Okay, then there's something I really don't understand.  The **usual** way to compute the linearised Cartesian index of a zero-based IJK-tuple is
```math
g = i + n_x\cdot(j + n_y\cdot k)
```
and the way to recover the IJK tuple from $g$ is then
```math
i = g\, \mathrm{mod}\, n_x, \quad
j = \lfloor g / n_x \rfloor\, \mathrm{mod}\, n_y, \quad
k = \lfloor g / (n_x \cdot n_y) \rfloor
```

> We take the global index and compute i and j to determine whether the connection between the two cells is an NNC or not below.

Sure, but the derivation of $j$, if it's actually supposed to be the J component of the cell's IJK index tuple, is suspicious to me since it uses `nz` instead of `ny`.

**Comment by blattms** [comment]
Sorry for my sloppy reading. Missed that aspect. That looks indeed strange/wrong. Also: why don't we also need to use k for the determination?

Maybe we should reuse`GridDims::getijk` here to prevent confusion?

**Comment by bska** [comment]
> Missed [the $n_y$ vs. $n_z$] aspect. That looks indeed strange/wrong

Okay, cool.  I was beginning to think I was losing my mind.

> Maybe we should reuse `GridDims::getijk` here to prevent confusion?

Yes, I think that'd be a great idea.  Unless you want to do the work, I can create a PR to that effect.

> Also: why don't we also need to use k for the determination?

I don't know.  It is, of course, possible that the original code did need to care about pinched-out layers, but nowadays the possibility that cells (I,J,K) and (I,J,K+3) would be connected across a pinch-out.  I **think** that would classify as a non-neighbouring connection for the purpose of MULTREGT, but I'm not completely sure.

**Comment by blattms** [comment]
> I don't know. It is, of course, possible that the original code did need to care about pinched-out layers, but nowadays the possibility that cells (I,J,K) and (I,J,K+3) would be connected across a pinch-out. I think that would classify as a non-neighbouring connection for the purpose of MULTREGT, but I'm not completely sure.

I think it does. All the documentatuion says so, all the code treats it like this (e.g. when writing out NNCs)

**Comment by blattms** [comment]
Concerning work: Yes please create the PR.

**Comment by bska** [comment]
> Concerning work: Yes please create the PR.

Please see PR #3639 for my proposed change.

**Comment by blattms** [comment]
Closing this as the PR is merged.
