### ISSUE TITLE
Remove messagecontainer

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#363]
Before mergin opm-parser into opm-common it was a point that opm-parser should be standalone; i.e. it could not depend on code from opm-common. Specifically this implied that the logging framework was not available to code in opm-parser, and instead a utility class `MessageContainer` was created to temporarily hold on to messages generated during the parsing process, and then subsequently replayed to the logging system afterwards.

Now that the parser code *has* access to the logger the code should issue normal logging calls and the `MessageContainer`class should be removed.

**Comment by atgeirr** [comment]
Is it worth it? I imagine it would be a somewhat intrusive change? Maybe not changing the logging calls themselves (they probably map well), but removing the messagecontainers from classes and interfaces etc.

**Comment by joakim-hove** [comment]
> Is it worth it? 

Yes - that is how we keep the yard clean!

>I imagine it would be a somewhat intrusive change?

I have not looked - but I am quite certain it is a small effort.

**Comment by joakim-hove** [comment]
Done in #368
