### ISSUE TITLE
Difference between mpi-default-bin and mpi-default-dev

### ISSUE THREAD

**Issue by Bakh** [OPM/opm-common#3647]
1) According to the OPM FLOW REFERENCE MANUAL (2023-04) -> 2.1 INSTALLING OPM FLOW -> 2.1.1 UBUNTU LINUX 20.04 (64-BIT VERSION ONLY) AND HIGHER
... to install the opm-simulators programs ... and their dependencies:
sudo apt-get install mpi-default-bin
...
2) On the other hand, according to the https://opm-project.org/?page_id=239 -> PREREQUISITES -> Ubuntu binaries (for Ubuntu 20.04 or 22.04)
// MPI for parallel programs
sudo apt-get install -y mpi-default-dev
...

Question:
What is the difference between results of the mpi-default-bin and mpi-default-dev?

**Comment by akva2** [comment]
dev is development headers and libraries (e.g. libmpi.so and mpi.h), bin is the binaries (e.g. mpirun). first is required to compile, second is required to run.

**Comment by blattms** [comment]
Closing this as it is answered.

**Comment by Bakh** [comment]
Thanks!
