### ISSUE TITLE
Buckley-Leverett 1D

### ISSUE THREAD

**Issue by anaxsouza** [OPM/opm-common#3663]
Currently I'm trying to create a base model for 1D Buckley-Leverett case, the problem is that the producer well isn't in right place, I tried almost everything, and the producer well keeps in the same location of the injector well. I'm leaving the code in annex, if someone can help me.
[base_bl.txt](https://github.com/OPM/opm-common/files/12515368/base_bl.txt)

**Comment by goncalvesmachadoc** [comment]
Hi @anaxsouza. Note your model only have one cell in x-direction and y-direction in DIMENS, meaning, max i and j are equal to one. Therefore you cannot have a well at i = 100 at WELSPECS. If you want we can have a quick call and  I can help you out to set a model.

**Comment by anaxsouza** [comment]
Hi @goncalvesmachadoc I really appreciate your kindness, when it is possible for you to appoint a video call with me?

**Comment by goncalvesmachadoc** [comment]
That's my contact so we can make a appointment: cintia.machado@tno.nl
