### ISSUE TITLE
Use 'installed' versions of the build modules?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#37]
When the build system was in opm-cmake I used to do (roughly):

1. fetch and update opm-cmake
2. `cmake -DCMAKE_INSTALL_PREFIX=/path/to/common/share`

In a regular Jenkins job; and then when building module `opm-xxx` I would configure with `cmake -DOPM_CMAKE_ROOT=/path/to/common/share` - unless I was actually updating the build system (which was *quite seldom*) - this worked fine.

However now it seems that `opm-common` does not install the cmake modules - so suddenly sibling builds have become mandatory; at least `opm-common` must be found in the sibling search? Is this by design - or an oversight of some kind?

**Comment by akva2** [comment]
oversight. fix coming up.

**Comment by joakim-hove** [comment]
> oversight. fix coming up.

Cool ;-)
