### ISSUE TITLE
Unnecessary population of thcwaterData

### ISSUE THREAD

**Issue by aritorto** [OPM/opm-common#3825]
https://github.com/OPM/opm-common/blob/a147c2a4663eb1d999f77ff0da9cd71fbb25054c/src/opm/material/thermal/EclThermalLawManager.cpp#L241

Is this correct? thcwaterData is populated twice. Is one of them unnecessary? If that the case, shall we keep the one inside the if-statement?

**Comment by blattms** [comment]
I am probably not very knowledgeable in this region, but I guess you are right and we should probably ditch the initial unconditional initialization at [EclThermalLawManager.cpp#L229](https://github.com/OPM/opm-common/blame/a147c2a4663eb1d999f77ff0da9cd71fbb25054c/src/opm/material/thermal/EclThermalLawManager.cpp#L229)
