### ISSUE TITLE
SSL cerificate of the CI system expired

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-common#384]
The SSL certificate of the jenkins server has expired yesterday which yields a scary browser warning and necessitates to add a security exception when trying to access ci.opm-project.org

**Comment by andlaus** [comment]
(note that this is not really an opm-common issue, but I don't know where else to put it.)

**Comment by alfbr** [comment]
Certificate updated, should work fine now. Thanks for reporting!

**Comment by andlaus** [comment]
thanks
