### ISSUE TITLE
Why Does `Summary.cpp:find_wells()` Use All Wells at Simulation End for its Field Vectors?

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#417]
I was reading through [`Summary.cpp`](https://github.com/OPM/opm-common/blob/d168e9ff67267c9dee0fea9d98866f024ff392a9/src/opm/output/eclipse/Summary.cpp) and in particular helper function [`find_wells()`](https://github.com/OPM/opm-common/blob/d168e9ff67267c9dee0fea9d98866f024ff392a9/src/opm/output/eclipse/Summary.cpp#L751-L754) which gets [called](https://github.com/OPM/opm-common/blob/d168e9ff67267c9dee0fea9d98866f024ff392a9/src/opm/output/eclipse/Summary.cpp#L1050) as part of `Summary::add_timestep()`'s handling of preconfigured "derived" summary vectors pertaining to wells, groups, fields, and connections/completions.

In the case of a "Field" vector (e.g., "FOPT"), function `find_wells()` will [return](https://github.com/OPM/opm-common/blob/d168e9ff67267c9dee0fea9d98866f024ff392a9/src/opm/output/eclipse/Summary.cpp#L771-L772)
```C++
schedule.getWells();
```
which is all wells present at the end of the simulation run as opposed to those that are active/present at the pertinent `sim_step`.  Contrariwise, the "Group" vectors are restricted to those wells that are in the relevant group at the particular `time_step`.

Is that distinction intentional?

**Comment by joakim-hove** [comment]
> Is that distinction intentional?

No.

The important thing is that when the summary header is gathered the `schedule.getWells()` for all wells should be used, whereas when calculations are done - i.e. all wells in a group are summed over, you only need to use the wells defined at the particular instant; although summing over all wells should not harm.

**Comment by bska** [comment]
> when the summary header is gathered the schedule.getWells() for all wells should be used,

Okay.  Does "gathering headers" mean "constructing the `Summary::ecl_sum` data member"?  If so, then function `find_wells()` is not used as part of that process.  Function `find_wells()` is only used as part of `add_timestep()` which is in the context of a particular simulation step.

**Comment by bska** [comment]
I'm closing this as no longer relevant.
