### ISSUE TITLE
Use of .cpp files in opm-common

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-common#48]
I would like to add classes with .cpp files to opm-common. Is this possible currently (i.e. files will be compiled, put in a library, and linked to by downstream modules)? Separately: what about unit tests?

Also: if anyone is strongly opposed to this, please tell us why!

**Comment by andlaus** [comment]
saying that I'm *strongly* opposed is too much, but I find it pretty cumbersome (and hampering to productivity) if having to recompile all modules in the dependency chain of the simulator just because a line in the basic infrastructural code was changed. (Case in point: if I change something in opm-material I'll only have to wait ~20 seconds until the change is in ebos but it takes about 2 minutes to get it into flow.)

**Comment by joakim-hove** [comment]
I would very much prefer the opm-common repo to contain cpp code and create a library. 

We organize the source code in different files to keep the overview, and in the same way we organize the code in different modules - my recent experience with working with header only implementation is that the module - module dependencies get opaque to a new developer, and unnecessarily difficult to understand. Case in point:

1. To debug opm-material you must build opm-core or possible other downstream modules - now that is leaking the abstractions.
2. The header: `thresholdPressures.hpp` in opm-core *fails to compile* when building opm-core.

> I'll only have to wait ~20 seconds until the change is in ebos but it takes about 2 minutes to get it into 

Well - at least for me there is a flip side to this argument; understanding and debugging (other peoples) header only code takes much longer time.

**Comment by andlaus** [comment]
> To debug opm-material you must build opm-core or possible other downstream modules - now that is leaking the abstractions.

would you mind elaborating why this is different between header-only and traditional libraries? If debugging a bug in e.g. the EQUIL init code you have to go down through the autodiff wrapper to opm-core.

> The header: thresholdPressures.hpp in opm-core fails to compile when building opm-core.

I also fail to see any correlation of this with the current issue.

>>  I'll only have to wait ~20 seconds until the change is in ebos but it takes about 2 minutes to get it into
>
> Well - at least for me there is a flip side to this argument; understanding and debugging (other peoples) header only code takes much longer time.

I think it is mostly a matter of taste (and I guess we all agree that it does not matter at all to users): IMO developers who are in favour for compiled libraries and complain about long build chains argue pretty inconsistently, though.

**Comment by joakim-hove** [comment]
> would you mind elaborating why this is different between header-only and traditional libraries? I

Well - I realize this is a matter of taste and personal opinion. But the point was that when you did `make` in the `opm-material` repository a significant fraction of the code was never seen by the compiler; and you had to go to a downstream module which instantiated the classes in `opm-material` to check the code in `opm-material`. My assumption is that when I do 
```
make 
ctest
```
in a repo I have a guarantee that the code is reasonably sane - it should not be necessary to go to a downstream module to check the code compiles at all. This will improve with the tests which are  in the pipeline for `opm-material.

>>The header: thresholdPressures.hpp in opm-core fails to compile when building opm-core.

>I also fail to see any correlation of this with the current issue.

Well - the `thresholdPrssures.hpp` is an example of a header-only (which I am skeptical to) - and to me the fact that a part of a repository can not even compile when issuing `make` in that repository is not very sound.

I'll back off now :-)

**Comment by andlaus** [comment]
> Well - I realize this is a matter of taste and personal opinion. But the point was that when you did make in the opm-material repository a significant fraction of the code was never seen by the compiler; [...]

right. but that was due to insufficient unit tests (and should hopefully be fixed soon). note that the same story applies to `opm-core` ;)

let's compromise by saying that adding cpp files to `opm-common` is okay but that the code must come with decent unit tests. (The same requirement should apply to template code.)

**Comment by atgeirr** [comment]
> let's compromise by saying that adding cpp files to opm-common is okay but that the code must come with decent unit tests. (The same requirement should apply to template code.)

I agree, and with that I'll call it a consensus and close this issue. There are still *technical* questions, but those can be made separately.
