### ISSUE TITLE
Error: Problem: Solver convergence failure

### ISSUE THREAD

**Issue by camilomalagon** [OPM/opm-common#508]
Hi,
I am trying to run an ECLIPSE file on Flow but beside some issues with some keywords, I get an error that I do not know how to solve.
When running the simulator I get the error:

`Problem: Solver convergence failure - Numerical problem encountered Timestep chopped to -nan days`

I am attaching a screenshot of the whole window for more details. 

I am running in Ubuntu 18.04.1 
![error on rema](https://user-images.githubusercontent.com/31506285/46212292-ece65080-c335-11e8-8ac2-962d93ec2a9b.png)

Thanks

**Comment by GitPaean** [comment]
Hi, 

It looks like from the very beginning, some NaN joined the simulation and ruined the whole simulation. 

It is possible Flow does not support some keywords well and it results in some NaN values.  There is no  way to tell without the actual DATA file.

**Comment by camilomalagon** [comment]
Hi, Thanks 
Here I am attaching the file.
[REMA.zip](https://github.com/OPM/opm-common/files/2434871/REMA.zip)
I appreciate you looking in to it to see what could be going on.

Cheers

**Comment by GitPaean** [comment]
Hi, Thanks for providing the DATA. With a very brief glance, it looks like it is using Fetkovich Aquifer. With my understanding, it is under development. Please refer to the PR to see the details, https://github.com/OPM/opm-common/pull/507 .  

The parsing of the Fetkovich Aquifer is still in progress, basically, the functionality is not there yet. I am not saying this is exactly the reason that caused problem, while we do not have the complete support of the functionality that is necessary to run your DATA file in a complete way yet. 

Hope the information is helpful.

**Comment by camilomalagon** [comment]
Hi,
I can see on page 609 of OPM manual that numerical aquifers are not supported neither.
I guess I will have to simulate with a Grid cell aquifer.
Thank you for the support.
Camilo
