### ISSUE TITLE
Is There a Reason for TimeMap Doing Explicit Arithmetic for Time Deltas as "double"?

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#509]
Looking at commit c9af992b7 (PR OPM/opm-parser#1104), it seems that [`getTotalTime`](https://github.com/OPM/opm-common/blob/af18b76d485438866342c9f412c54522fdb296bc/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L84-L90), [`getTimeStepLength`](https://github.com/OPM/opm-common/blob/af18b76d485438866342c9f412c54522fdb296bc/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L196-L203), and [`getTimePassedUntil`](https://github.com/OPM/opm-common/blob/af18b76d485438866342c9f412c54522fdb296bc/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L205-L212) were translated mostly literally from using `boost::posix_time::ptime` to using `std::time_t`.  While that was probably reasonable in context, I wonder if that reasoning still holds.

Is there any reason to not apply something like the patch below (provided all tests pass &c)?

---

```diff
diff --git a/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp b/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
index bedb6eae..2de8055f 100644
--- a/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
+++ b/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
@@ -85,8 +85,9 @@ namespace Opm {
     {
         if (m_timeList.size() < 2)
             return 0.0;
-        const time_t deltaT = m_timeList.back() - m_timeList.front();
-        return static_cast<double>(deltaT);
+
+        return std::difftime(this->m_timeList.back(),
+                             this->m_timeList.front());
     }
 
     void TimeMap::addTime(std::time_t newTime) {
@@ -196,19 +197,17 @@ namespace Opm {
     double TimeMap::getTimeStepLength(size_t tStepIdx) const
     {
         assert(tStepIdx < numTimesteps());
-        const std::time_t t1 = m_timeList[tStepIdx];
-        const std::time_t t2 = m_timeList[tStepIdx + 1];
-        const std::time_t deltaT = t2 - t1;
-        return static_cast<double>(deltaT);
+
+        return std::difftime(this->m_timeList[tStepIdx + 1],
+                             this->m_timeList[tStepIdx + 0]);
     }
 
     double TimeMap::getTimePassedUntil(size_t tLevelIdx) const
     {
         assert(tLevelIdx < m_timeList.size());
-        const std::time_t t1 = m_timeList.front();
-        const std::time_t t2 = m_timeList[tLevelIdx];
-        const std::time_t deltaT = t2 - t1;
-        return static_cast<double>(deltaT);
+
+        return std::difftime(this->m_timeList[tLevelIdx],
+                             this->m_timeList.front());
     }
```

**Comment by joakim-hove** [comment]
I think the proposed patch makes very much sense.

My (ideal) algorithm:
```
if (looks_better() && all_tests_pass())
   merge();
```
If we can not follow that algorithm that means our testing is lacking; and I am actually willing to discover that through a premature merge.
