### ISSUE TITLE
GDFILE not supported

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-common#523]
Just noticed OPM does not support GDFILE keyword to read binary EGRID files as I got the following error message.  

`Program threw an exception: PARSE_UNKNOWN_KEYWORD: Keyword GDFILE not recognized.`

Is there any plans to support it in the near future? Grid info has to be read in ASCII format (like from GRDECL files)?

**Comment by joakim-hove** [comment]
I was not aware of that keyword - but *if* it is just a pointer to a normal EGRID file it should be quite simple to support.

**Comment by sogoogos** [comment]
I think so. It is just a keyword for importing a binary grid (EGRID) file. 
http://petrofaq.org/wiki/Eclipse_Input_Data#ECLIPSE_Grid_Binary_Format

That would be great if you could support it.

**Comment by OPMUSER** [comment]
@joakim-hove the keyword reads both EGRID and GRID files for geometry data and can only be used in the GRID section. 

There is also the IMPORT keyword that can be used in the GRID, EDIT, PROPS, REGIONS and SOLUTION sections and appears to have more flexibility.

**Comment by sogoogos** [comment]
@joakim-hove I have noticed you merged the commit for handling GDFILE. I cloned and installed it. However, I still got: 

`Failed to create valid EclipseState object.
Exception caught: Failed to load grid from: CASE_146_H069_GRID.EGRID
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Failed to load grid from: CASE_146_H069_GRID.EGRID`

**Comment by joakim-hove** [comment]
OK;

that was unfortunate. For debugging:

1. Do you still have the `SPECGRID` or `DIMENS` keyword in the file? That should be OK.
2. If you have not done that - can you try running `flow` from the same location in the filesystem as the `.DATA` file?

**Comment by joakim-hove** [comment]
If you are happy to test a feature branch you could give this a spin: https://github.com/OPM/opm-common/pull/533

**Comment by sogoogos** [comment]
@joakim-hove  2. worked. Thank you!

**Comment by OPMUSER** [comment]
@joakim-hove GDFILE keyword documented in 2018-10 manual.

**Comment by OPMUSER** [comment]
Did the GDFILE keyword make into the 2018-1o release as I'm getting same error as @sogoogos with this version?

**Comment by joakim-hove** [comment]
No - I am sorry, don't know what happened. Will try to look at it.

**Comment by joakim-hove** [comment]
OK - I have checked - the `GDFILE` was supported here: https://github.com/OPM/opm-common/pull/530 - so it did not make it into 2018.10, but should be there for 2019.04.
