### ISSUE TITLE
FIPNUM jason file missing from keywords

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#524]
The FIPNUM jason file is missing from keyword definitions, does not appear to cause problems even though it is most input decks.

**Comment by joakim-hove** [comment]
It is covered by the keyword [`FIP_PROBE`](https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FIP_PROBE) which catches *all* keywords starting with `FIP`
