### ISSUE TITLE
Build system forces client module version

### ISSUE THREAD

**Issue by rolk** [OPM/opm-common#527]
I have a module with the following two lines in `dune.module`:

    Version: 2018.04	
    Depends: ewoms (>= 2018.04)

After upgrading the OPM stack to 2018.10, I get this message when trying to configure:

    CMake Warning at src/opm-common/cmake/Modules/OpmFind.cmake:185 (find_package):
      Could not find a configuration file for package "ewoms" that is compatible with requested version "2018.04".

      The following configuration files were considered but not accepted:

        bld/ewoms/ewoms-config.cmake, version: 2018.10
        bld/share/cmake/ewoms/ewoms-config.cmake, version: 2018.10

If I change the version line in *my* module to:

    Version: 2018.10

everything works again.

So the build system forces all modules to have the same version number. I totally see that this makes sense in between the OPM modules themselves, but I wonder if it was intentional that this should also apply to "3rd-party" modules. The change seemed to have been introduced in 9737538.

Feel free to close as "work as intended" if it really is.

**Comment by bska** [comment]
@rolk: Is this issue still relevant for you?
