### ISSUE TITLE
Is there a way to know which report steps are available in the RESTART file?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-common#536]
With the available report steps in the RESTART file, we can restart the simulation. 

Thanks.

**Comment by joakim-hove** [comment]
It is in the `SEQNUM`keyword of the restart files. There are many ways to find that; from the `libecl` toolchest you can [all code untested]:

1. [If you have set `-DBUILD_APPLICATIONS=ON`] Use the small binary `convert.x`:
```bash
ecl/install/bin> convert.x RESTART_FILE.UNRST
```
that will create a file `RESTART_FILE.FUNRST` which can be read with your favorite text editor.

2. [If you have the Python extensions - `-DENABLE_PYTHON=ON`]:
```python
#!/usr/bin/env python
from ecl.eclfile import EclFile
import sys

f = EclFile(sys.argv[1])
for kw in f["SEQNUM"]:
     print kw[0]
```

3. A small C/C++ application:
```C++
#include <ert/ecl/ecl_file.hpp>
#include <ert/ecl/ecl_kw.hpp>


int main(int argc, char **argv) {
     ecl_file_type * file = ecl_file_open(argv[1], 0);
     for (int i=0; i < ecl_file_get_num_named_kw(file, "SEQNUM"); i++) {
         const ecl_kw_type * seqnum = ecl_file_iget_named_kw( file, "SEQNUM", i);
         printf("Report step: %d \n",ecl_kw_iget_int(seqnum , 0));
    } 
    ecl_file_close(file);
}
```

Resinsight surely knows this - but I am not sure whetherit is displayed.

**Comment by GitPaean** [comment]
Thanks. I might have used the first option long time ago, while all these options are good solutions to me. Closing the issue now since the question got well answered.
