### ISSUE TITLE
Parser returns no NNC if included from separate file

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#550]
I just tested master (with my editnnc patch) and the pr OPM/opm-tests#65 and during the NNC processing the list is actually empty? What strikes me is that the NNCs for that problem are defined
in an external file that gets included via:
```
INCLUDE
 'include/edit_nnc.inc' /
```

Could that be the problem?

**Comment by blattms** [comment]
Input from @joakim-hove would be appreciated

**Comment by joakim-hove** [comment]
I will look later today. My initial reaction is that the use of an include file should not pose a problem.

**Comment by blattms** [comment]
there seems to be no explicit NNC definition anywhere in the files of PR OPM/opm-tests#65

**Comment by joakim-hove** [comment]
Ok
