### ISSUE TITLE
EclipseState is supposed to provide the schedule?!

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-common#552]
If my understanding of this is correct, the `EclipseState` is supposed to represent a fully internalized version of the input deck where most of the quirks of the input format have been dealt with?

I seems that it does not provide access to the scheduling information, though. i.e., the `Schedule` object needs to be created externally. IMO this is pretty clunky, but maybe I missed something? (I hope so) If I did, how to get access to a `Schedule` object from `EclipseState`?

**Comment by bska** [comment]
> I seems that it does not provide access to the scheduling information, though. i.e., the `Schedule` object needs to be created externally.

See PR OPM/opm-parser#1138.

**Comment by andlaus** [comment]
was there any good reason for that design change, there are exactly zero reasons for it in the discussion. IMO, this constitutes a layering violation.

**Comment by joakim-hove** [comment]
> was there any good reason for that design change, there are exactly zero reasons for it in the discussion. 

I agree there should have been a reasoning presented in the PR. The was/is to enable/simplify while-simulating changes to the driving conditions, which are all in the Schedule. It should be said that that has not yet been realized, but e.g. the work on `ACTIONX` is in heading in that direction. 

> this constitutes a layering violation.

That seems to be your standard complaint when there is something you do not like?!

**Comment by andlaus** [comment]
> That seems to be your standard complaint when there is something you do not like?!

no, that's my standard complaint when I see something that logically belongs somewhere else. (the simulator should not be forced to deal with low-level parser objects IMO.) do you disagree on that assessment? if yes, why?

**Comment by andlaus** [comment]
BTW: this design makes it much harder to internalize internal changes to these objects (ACTIONX (?)), because EclipseState is no longer aware of them. IOW, I would be pretty surprised if ACTIONX could be implemented without significant simulator support. (please surprise me!)

**Comment by joakim-hove** [comment]
> I would be pretty surprised if ACTIONX could be implemented without significant simulator support. 

Simulator support will be needed - but *only* `Schedule` instance will be mutated.
