### ISSUE TITLE
Problems compiling summaryIntegrationTest

### ISSUE THREAD

**Issue by kel85uk** [OPM/opm-common#582]
I updated my master branch to commit 49eda9fc7208b8e142814e8e97fd0e6415d16573 and I get problems with the compilation of summaryIntegrationTest.cpp

![image](https://user-images.githubusercontent.com/6287181/49856986-9abfb200-fdf1-11e8-87ec-17a8eba19f32.png)

**Comment by joakim-hove** [comment]
I don't know how far behind your opm-common branch was; but have you taken the libecl upgrade mentioned here into account: https://github.com/OPM/opm-common/pull/575

**Comment by kel85uk** [comment]
Perfect, solved it. Thanks!

**Comment by kel85uk** [comment]
Maybe having libecl and other dependencies as a git submodule would make sense so a noob user such as myself would always get a correct version of dependencies?

**Comment by joakim-hove** [comment]
Yes - that might be a good idea.

**Comment by kel85uk** [comment]
Shall I make an issue for git submodule and put it as a low priority but at least it's kept in mind for the future?

**Comment by kel85uk** [comment]
When used correctly, it can be beneficial, then again, it's the keywords of "used correctly"... I'll just open the issue and the main OPM developers can have a debate on it.
