### ISSUE TITLE
New ParseContext error mode?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#600]
When the error handlers are in the strict mode: `InputError::THROW_EXCEPTION` an exception is thrown immediately, in the (quite common) situation that there are multiple errors, only the first will be handled with this setting. I suggest a new error mode - e.g. `InputError::DELAYED_EXCEPTION` which will collect all errors, and then continue until the `Deck / EclipseState` has been completely assembled.

If there have been errors during the assembly all error messages will be written to `stderr` - and the application as a whole will terminate. This error mode should mainly be geared towards developers/debugging - combined with a command line option like:
```
flow --strict-mode CASE.DATA
``` 
one should have a good starting point for debugging.

My loose thought has been to implement a small container class `ErrorList` which assembles these errors, that should work nicely - but the disadvantage is that *maaany* function calls will change their signature from:
```
... some_method(..., const ParseContext& context);
```
to
```
...some_method(..., const ParseContext& context, ErrorList& errors);
```
opinions on this?

**Comment by OPMUSER** [comment]
Fantastic, I think this should be the default behavior, so I don't see the need for another command line parameter to switch this ON/OFF, as it should always be ON - like the commercial simulator. At the moment fixing one error at a time is very time consuming. I would also echo to the PRT file the complete deck first, then rewind the deck file and then start processing, that way the user has the input deck and the error log in the same file. 

If you made this the standard behavior will this avoid changing the many function calls?

It would also be good to implement ECHO ON and ECHO OFF to avoid dumping all the grid data to the PRT file, but that can wait for another day.

**Comment by joakim-hove** [comment]
> Fantastic, I think this should be the default behavior, so I don't see the need for another command line parameter to switch this ON/OFF, as it should always be ON - like the commercial simulator. 

What we could achieve with the switch was that all errors - including those which are currently ignored, or only treated as warnings, would be flagged as errors. But yes - the default fatal behavior could be to throw a delayed exception.

> I would also echo to the PRT file the complete deck first, then rewind the deck file and then start processing, that way the user has the input deck and the error log in the same file.

I have no strong opinions on how useful this feature is; I have always found that behavior from Eclipse a bit weird. But anyway to support this is quite orthogonal to the different error modes - so the decision whether to implement that can be taken independently. 

> If you made this the standard behavior will this avoid changing the many function calls?

No - the function calls must still be changed, not that that is such a chore - more that the function signatures get longer and less comfortable for the developers - not a really big deal.

**Comment by alfbr** [comment]
This is a welcome addition at my end. Thank you!

> it should always be ON - like the commercial simulator

As @joakim-hove explains, this is actually two issues. One is to have strict parsing, which basically not ignoring any errors from the input deck. This is a stricter parsing mode than the commercial simulator. It is currently off by default to avoid frustrating user with what may be conceived pedantic behaviour from the simulator. Personally, I think we need to have this off by default at least for a couple of years to avoid pushing users away. Having the ability to turn it on like suggested here is very welcome for quality assuring purposes though.

The other issue is whether the simulator should stop at errors that are grave enough for us not to ignore. These are typically errors that have a high probability of impacting simulation results. This is actually quite problematic to turn off by default. While many users may prefer it, the engineers responsible for QA do not want to open that door. What you suggest is probably something in between, where the simulator stops but only after reporting all errors seen in the deck. This can be done I guess, but I am not sure how much added value it will provide.

**Comment by atgeirr** [comment]
We are in fact working on a feature quite similar to the `ErrorList` you propose (and also similar in spirit to the old `MessageContainer`), namely a container for log messages. The purpose is to be able to accumulate log messages from different processes (for example triggered by a well only on one process) and then log them all on the output rank process. The container class itself will not know any MPI and be quite simple, the gathering function will be separate (similar to how the `ConvergenceReport` class and `gatherConvergenceReport()` functions were done). It will replace the WellSwitchingLogger, but be more general, allowing us to fix many cases of incorrect logging being done in parallel.

My question is if these two things are so close we should unify them, or if your need (just exceptions) is so much simpler it makes sense to have its own. Collecting exceptions for throwing on all ranks is however also a utility we should have.

**Comment by OPMUSER** [comment]
The reason for the echoing of the input deck to the PRT file is to ensure that deck submitted is the deck the user "thinks" is being run. For example it is not uncommon to make changes to the input deck and rerun without saving the input deck first. I have done this myself. 

`
it should always be ON - like the commercial simulator and --strict-mode`

@alfbr I see your point on this for and so I think that what @joakim-hove has suggested is okay in this context for the --strict-mode parsing. However, for "normal" errors that stop flow from running we still need to collect all these errors at the end of the parsing so the users has the opportunity to fix multiple errors. So what about treating the "strict" errors as WARNINGS instead, so that --strict-mode=WARN and strict-mode=ERROR options. But like @alfbr said if the number of Warning message are verbose it will frighten off users. 

Alternatively, once flow finds an error we could just switch to NOSIM mode and then collect all the run stopping error messages. Being able to get all the errors messages that STOP flow from running in one pass will greatly improve the user experience.

**Comment by joakim-hove** [comment]
> We are in fact working on a feature quite similar to the ErrorList you propose (and also similar in spirit to the old MessageContainer), namely a container for log messages.

yes - what I had in my mind was actually something quite similar to the old `MessageContainer` ....

The api/implementation I have thought of would be extremely simple; i.e. something like this:

```
class ErrorList {
    add_error( const std::string& key, const std::string& msg);
    add_warning( const std::string& key, const std::string msg);
    operator bool() const;
    exit(const std::string& msg);
}
```

Then at the end of the assembly this will be evaluated as:
```
if (error_list)
   error_list.exit("Fatal errors were encountered while parsing the input deck");
```

My gut feeling is that it will be simplest to create two implementations?

**Comment by atgeirr** [comment]
> My gut feeling is that it will be simplest to create two implementations?

Quite possible. The API we have in mind is to be similar to the OpmLog convenience functions, i.e. `warning(const std::string& tag, const std::string& msg)`, similar with `info`, `problem`, `note` etc. Then a function `logNow()` or similar will actually do the logging (using the regular OpmLog facility). However your suggestion includes not only errors (presumably causing termination), but also warnings, so there is some overlap.

**Comment by joakim-hove** [comment]
This has been implemented
