### ISSUE TITLE
BUG MINVALUE

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#623]
Unit conversion is not applied correctly when using the `MINVALUE` keyword
```
MINVALUE
'PERMX' 200  /
/
```
gives `PERMX` values of `200m^2` instead of `200 mD`.

Could this be a problem with `ADD` and `PERMX` as well?

**Comment by joakim-hove** [comment]
> Could this be a problem with ADD and PERMX as well?

Should not - but should not be a problem with `MINVALUE`either - so ... Can you post more (complete ?) deck content?

**Comment by totto82** [comment]
Just add

MINVALUE
 PERMX 200 /
/

to SPE1CASE2 at the end of the grid section.
