### ISSUE TITLE
For those about to ... work with wells :-)

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#624]
The `DynamicState<T>` class has proved to be a quite successful approach to working with dynamic data - IMHO. Lately I have used a pattern where the `Schedule` class has a member:
```C++
DynamicState<std::shared_ptr<T>>
```
The use of `std::shared_ptr<T>` is an implementation detail which does not leak out of the `Schedule.cpp` implementation. See e.g. the members `wtest_config` and `wlist_manager` in the `Schedule` class - this pattern has been quite comfortable to work with. 

This in contrast to the Wells owned by the `Schedule` class, the well objects contain a large list of internal `DynamicState<T>` objects. I would like to "invert" this, so that the `Well`class becomes a much simpler - immutable object, and changes are implemented by inserting a new `Well` instance in a `DynamicState<Well>` member owned by the `Schedule` object. I think working with wells (at least parser near) - will be simpler that way, and the well code (which is quite large ...) will be easier to maintain!

Opinions?!

**Comment by bska** [comment]
Is this issue still relevant?  It would appear that the pertinent PRs have all been merged into master.

**Comment by bska** [comment]
> Is this issue still relevant? It would appear that the pertinent PRs have all been merged into master.

This question still stands.
