### ISSUE TITLE
cannot build with an old version of clang

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-common#631]
I got the following error with the clang version Apple LLVM version 8.0.0 (clang-800.0.42.1):
```
[ 23%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp.o
[ 24%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp.o
[ 24%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp.o
[ 24%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.cpp.o
/Volumes/Transcend/rmine/OPM_master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp:75:14: error: no member named 'strtod' in namespace 'std'
        std::strtod(lower_arg.c_str(), &end_ptr);
        ~~~~~^
/Volumes/Transcend/rmine/OPM_master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp:139:25: error: use of undeclared identifier 'strtod'; did you
      mean 'strtok'?
        return ASTNode( strtod(current.value.c_str(), nullptr) );
                        ^~~~~~
                        strtok
/usr/include/string.h:90:7: note: 'strtok' declared here
char    *strtok(char *, const char *);
         ^
/Volumes/Transcend/rmine/OPM_master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp:139:32: error: cannot initialize a parameter of type 'char *'
      with an rvalue of type 'const value_type *' (aka 'const char *')
        return ASTNode( strtod(current.value.c_str(), nullptr) );
                               ^~~~~~~~~~~~~~~~~~~~~
/usr/include/string.h:90:20: note: passing argument to parameter here
char    *strtok(char *, const char *);
                      ^
3 errors generated.
make[2]: *** [CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/opmcommon.dir/all] Error 2
make: *** [all] Error 2
```

But I was able to build it with a newer one: Apple LLVM version 10.0.0 (clang-1000.10.44.4).

**Comment by atgeirr** [comment]
To use strtod in C++ one should include `<cstdlib>` and prefix it with `std::`. The reason it sometimes works anyway is that the inclusion happens indirectly, i.e. another header that is included from here includes cstdlib. Such behaviour can change between compilers and compiler versions. I think I already fixed this bug some time ago, but maybe someone made the same bug again...

If you still have the old compiler you could try adding the include and the std:: prefix, and see if that works.

**Comment by andlaus** [comment]
@sogoogos: I believe you need the recent fix for MINVALUE, so you are using the master version of opm-common (i.e., the bug crept in again after @atgeirr's fix)?

**Comment by sogoogos** [comment]
@atgeirr After adding include `<cstdlib>` in `src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp`,  I was able to build it with both versions. Should I pull request for this?

@andlaus Yes, I am using the latest master.

**Comment by bska** [comment]
> After adding include `<cstdlib>` in `ActionParser.cpp`, I was able to build it with both versions. Should I pull request for this?

Yes please!

**Comment by sogoogos** [comment]
Just made a pull request #634

**Comment by bska** [comment]
> Just made a pull request #634

Much appreciated.  I've launched a Jenkins build just to be on the safe side.
