### ISSUE TITLE
Linking Issues with ERT

### ISSUE THREAD

**Issue by WenPann** [OPM/opm-common#655]
Hi everyone,

I am trying to install OPM on a computing cluster TACC, but when I tried to build OPM-common, there is a linking problem which is shown below. It seems like that it cannot find ERT, but when I type `grep ecl_DIR CMakeCache.txt`, it can find the correct path in `Reservoir_Modeling/OPM7/share/cmake/ecl`. Can anyone help me?
```
[ 41%] Linking CXX executable bin/test_msim_ACTIONX
lib/libopmcommon.a(EclipseIO.cpp.o): In function `Opm::(anonymous namespace)::RFT::RFT(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/output/eclipse/EclipseIO.cpp:122: undefined reference to `ERT::EclFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ecl_file_enum, bool)'
lib/libopmcommon.a(EclipseIO.cpp.o): In function `Opm::EclipseIO::Impl::writeINITFile(Opm::data::Solution const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >, Opm::NNC const&) const':
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/output/eclipse/EclipseIO.cpp:241: undefined reference to `ERT::EclFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ecl_file_enum, bool)'
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/output/eclipse/EclipseIO.cpp:246: undefined reference to `ERT::FortIO::FortIO(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode, bool, bool)'
lib/libopmcommon.a(EclipseIO.cpp.o): In function `Opm::EclipseIO::Impl::writeEGRIDFile(Opm::NNC const&)':
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/output/eclipse/EclipseIO.cpp:382: undefined reference to `ERT::EclFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ecl_file_enum, bool)'
lib/libopmcommon.a(EclipseIO.cpp.o): In function `Opm::EclipseIO::writeTimeStep(int, bool, double, Opm::RestartValue, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<double, std::allocator<double> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<double, std::allocator<double> > > > > const&, std::map<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, double, std::less<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >, std::allocator<std::pair<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const, double> > > const&, bool)':
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/output/eclipse/EclipseIO.cpp:462: undefined reference to `ERT::EclFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ecl_file_enum, int, bool)'
lib/libopmcommon.a(IOConfig.cpp.o): In function `Opm::IOConfig::getRestartFileName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool) const':
/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp:196: undefined reference to `ERT::EclFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ecl_file_enum, int, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_msim_ACTIONX] Error 1
make[1]: *** [CMakeFiles/test_msim_ACTIONX.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bska** [comment]
> but when I tried to build OPM-common, there is a linking problem which is shown below
> but when I tried to build OPM-common, there is a linking problem which is shown below

Hi,

Thanks for reporting the issue.  I notice that you're using CMake's "Makefile" generator.  That's fortunate, because then we can delve deeper into the linker issue by looking at the makefiles.  Does the computer have Perl?  If so, can you run the following command from the top level of your opm-common build directory:
```sh
perl -ane 'map{print "$_\n"}split' CMakeFiles/test_msim_ACTIONX.dir/link.txt
```
My initial hunch is that the `libecl` library is too early on the link line.

Just for the record, below is what I get from the above on my Ubuntu 16,04 LTS laptop.  In my case, the `libecl.so.2.4` file is very close to the end of the link line and so this happens to work for me.  I'd be genuinely interested to see what you get, because it will at least inform our further analysis.

---

```
/usr/bin/g++-5
-std=c++14
-pipe
-pedantic
-Wall
-Wextra
-Wcast-align
-Wcast-qual
-Wchar-subscripts
-Wformat-nonliteral
-Wmissing-declarations
-Wpointer-arith
-Wredundant-decls
-Wundef
-Wwrite-strings
-fopenmp
-pthread
-ggdb3
-O0
-D_GLIBCXX_DEBUG=1
-D_GLIBCXX_DEBUG_PEDANTIC=1
-DDEBUG
CMakeFiles/test_msim_ACTIONX.dir/tests/msim/test_msim_ACTIONX.cpp.o
-o
bin/test_msim_ACTIONX
-L/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug
-rdynamic
lib/libmocksim.a
lib/libopmcommon.a
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_unit_test_framework-gcc54-mt-d-1_64.so
/home/bska/work/opm/inst/dbg/lib/libecl.so.2.4
-lm
-ldl
-pthread
-lz
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_system-gcc54-mt-d-1_64.so
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_filesystem-gcc54-mt-d-1_64.so
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_regex-gcc54-mt-d-1_64.so
-Wl,-rpath,/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug:/home/bska/work/opm/inst/dbg/lib
```

**Comment by WenPann** [comment]
Thanks for replying, I got the following message from the link file:
/opt/apps/gcc/7.1.0/bin/g++  
-std=c++14 
-pipe 
-Wall 
-fopenmp 
-pthread 
-O3 
-mtune=native 
-DNDEBUG  
-rdynamic CMakeFiles/test_msim_ACTIONX.dir/tests/msim/test_msim_ACTIONX.cpp.o  
-o 
bin/test_msim_ACTIONX  
-L/opt/apps/gcc7_1/boost/1.64/lib 
-Wl,-rpath,
/opt/apps/gcc7_1/boost/1.64/lib:/work/06101/wp4374/Reservoir_Modeling/OPM7/lib64 
lib/libmocksim.a 
lib/libopmcommon.a 
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so
 /work/06101/wp4374/Reservoir_Modeling/OPM7/lib64/libecl.so.2.4 
-lm 
-ldl 
-pthread 
-lz 
/opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so 
/opt/apps/gcc7_1/boost/1.64/lib/libboost_filesystem.so 
/opt/apps/gcc7_1/boost/1.64/lib/libboost_regex.so

It seems like the position of the library in the link line is similar to yours, may I know the version of OPM and libecl you installed?
Many thanks!

**Comment by bska** [comment]
> It seems like the position of the library in the link line is similar to yours, may I know the version of OPM and libecl you installed?

Agreed.  The structure of our link lines are very similar.  I notice that the position of the `-rpath` specification differs between the two cases, but otherwise there's nothing that stands out to me.  For what it's worth, I'm running the latest `master` sources of opm-common (ab737ab4d3) and libecl (Equinor/libecl@055fcfcc9e2f51bd98398dfe6ad487ad125289b1).

**Comment by joakim-hove** [comment]
I really don't know - but just some loose thoughts/questions:

1. You mention that you encounter these problems when installing on a particular computing cluster, does that imply that you can install successfully in another environment?

2. What are the specifications of the system you have problems - i.e. which operating system version?

3. The link problem you report is in a test `test_msim_ACTIONX` - which at least used by a odd-one-out when it came to the build system. I realize this does not really fix anything - but you could try building opm-common without the tests; just invoke `cmake` as:
```bash
bash% cmake . -DBUILD_TESTING=OFF
```

**Comment by WenPann** [comment]
> I really don't know - but just some loose thoughts/questions:
> 
> 1. You mention that you encounter these problems when installing on a particular computing cluster, does that imply that you can install successfully in another environment?
> 2. What are the specifications of the system you have problems - i.e. which operating system version?
> 3. The link problem you report is in a test `test_msim_ACTIONX` - which at least used by a odd-one-out when it came to the build system. I realize this does not really fix anything - but you could try building opm-common without the tests; just invoke `cmake` as:
> 
> ```shell
> bash% cmake . -DBUILD_TESTING=OFF
> ```

Yes, I can install it on my laptop which is Ubuntu16.04.5 LTS. The cluster is  Linux 7. 

Compared to the installation on my laptop, there are also more warnings when I tried to install it on the cluster, please see below. Maybe I should try a different version of boost or compiler?




n file included from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/base.hpp:28:0,
                 from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array.hpp:21,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp:27,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:40,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp:35:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<N>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:42:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:43:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<0>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:53:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:54:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
[ 19%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Runspec.cpp.o
[ 19%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.cpp.o
[ 20%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionContext.cpp.o
[ 20%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp.o
[ 20%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp.o
[ 20%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp.o
[ 20%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.cpp.o
[ 21%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp.o
[ 21%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp.o
In file included from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/base.hpp:28:0,
                 from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array.hpp:21,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp:27,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:40,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp:26:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<N>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:42:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:43:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<0>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:53:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:54:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
[ 21%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Connection.cpp.o
In file included from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/base.hpp:28:0,
                 from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array.hpp:21,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp:27,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:40,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Connection.cpp:33:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<N>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:42:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:43:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<0>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:53:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:54:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
[ 21%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Events.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Group.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/MessageLimits.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp.o
[ 23%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp.o
[ 23%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp.o
[ 23%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp.o
[ 23%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp.o
[ 24%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp.o
In file included from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/base.hpp:28:0,
                 from /opt/apps/gcc7_1/boost/1.64/include/boost/multi_array.hpp:21,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp:27,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:40,
                 from /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:53:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<N>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:42:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:43:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<0>::call(Array&, const IdxGen&, Call_Type)’:
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:53:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^~~~~~~~~~~
/opt/apps/gcc7_1/boost/1.64/include/boost/multi_array/concept_checks.hpp:54:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^~~~~

I will give it a try thanks！

**Comment by WenPann** [comment]
I attached the output from cmake process.

-- CMake version: 3.10.2
-- Linux distribution: CentOS Linux 7 (Core)
-- Target architecture: x86_64
-- Found Git: /opt/apps/git/2.9.0/bin/git (found version "2.9.0") 
-- Source code repository: git e00a5d5%
-- GNU C++ compiler version: 7.1.0
-- Linker: ld 2.28
-- Checking to see if CXX compiler accepts flag -Wl,--enable-new-dtags
-- Checking to see if CXX compiler accepts flag -Wl,--enable-new-dtags - yes
-- Precompiled headers: disabled
-- Build type: Debug
-- Checking to see if CXX compiler accepts flag -mtune=native
-- Checking to see if CXX compiler accepts flag -mtune=native - yes
-- All warnings enabled: -Wall
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Checking to see if CXX compiler accepts flag -pthread
-- Checking to see if CXX compiler accepts flag -pthread - yes
-- Could NOT find CppCheck (missing: CPPCHECK_PROGRAM) 
-- Disabling clang-check as CMAKE_EXPORT_COMPILE_COMMANDS is not enabled
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
--   regex
-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Performing Test HAVE_DYNAMIC_BOOST_TEST
-- Performing Test HAVE_DYNAMIC_BOOST_TEST - Success
-- Writing config file "/work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/build/config.h"...
-- This build defaults to installing in /work/06101/wp4374/Reservoir_Modeling/OPM7
-- Checking whether the file system is case-sensitive
-- File system is case-sensitive
-- Found Doxygen: /bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- Writing version information to local header project-version.h
-- Configuring done
-- Generating done
-- Build files have been written to: /work/06101/wp4374/Reservoir_Modeling/OPM7/opm-common/build

**Comment by alfbr** [comment]
Hi Sogo,

The simple solution to your linking issues is the following:
-download libecl from git in a neighbouring folder to opm-common, then the bulid system will automatically link towards that version ensuring that you get a successful build
-only build static version of libecl (check out the relevant cmake variable in libecl to disable the dynamic version), then you are sure to get a static binary, and hence no linking issues and your binaries will be portable

Good luck!
Alf

**Comment by bska** [comment]
@WenPann: Are you still seeing this issue?  We stopped linking to the libecl libraries as of the 2019.10 release of OPM Flow.
