### ISSUE TITLE
Compiling error (UDQSet.hpp)

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-common#658]
I got `ERROR:  implicit instantiation of undefined template` when compiling with `Apple LLVM version 10.0.0 (clang-1000.10.44.4)`.

Adding `#include <string>` in  `opm-common/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp` solved the problem. 

Should I make a pull request for this?

**Comment by joakim-hove** [comment]
Yes PR is cool - thank you.

**Comment by sogoogos** [comment]
Okay, just made it #659
