### ISSUE TITLE
strict parsing error

### ISSUE THREAD

**Issue by hnil** [OPM/opm-common#701]
Parsing with strict mode give strange error on all tested cases:
Example spe1/SPE1CASE1.DATA
```
flow SPE1CASE1.DATA --ecl-strict-parsing=true
**********************************************************************
*                                                                    *
*                      This is flow 2019.04-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see https://opm-project.org         *
*                                                                    *
**********************************************************************

Reading deck file '/data/hnil/GITHUB/opm-data/spe1/SPE1CASE1.DATA'


Errors:
  SIMULATOR_KEYWORD_NOT_SUPPORTED: Keyword 'NOECHO' is not supported by flow.
In file /data/hnil/GITHUB/opm-data/spe1/SPE1CASE1.DATA, line 75

  SIMULATOR_KEYWORD_NOT_SUPPORTED: Keyword 'ECHO' is not supported by flow.
In file /data/hnil/GITHUB/opm-data/spe1/SPE1CASE1.DATA, line 107

  SIMULATOR_KEYWORD_NOT_SUPPORTED: Keyword 'RPTSCHED' is not supported by flow.
In file /data/hnil/GITHUB/opm-data/spe1/SPE1CASE1.DATA, line 372

  SUMMARY_UNDEFINED_UDQ          : Summary output has been requested for UDQ keyword: SUMMARY but it has not been configured

terminate called after throwing an instance of 'std::runtime_error'
  what():  Unrecoverable errors were encountered while loading input.
Aborted (core dumped)
```

**Comment by joakim-hove** [comment]
> Parsing with strict mode give strange error on all tested cases

Perfectly logical errors to me .... I'll try &phone;

**Comment by bska** [comment]
> the deck requests output of a UDQ variable,

I'm probably missing something but I don't see anything related to UDQ at all in [SPE1CASE.DATA](https://github.com/OPM/opm-tests/blob/a00cd37828645dbe40e0ecde228f221c7d55cf0e/spe1/SPE1CASE1.DATA).  Rather, it **looks** as if the `ErrorContext` inadvertently characterises the `SUMMARY` keyword itself as a UDQ keyword.

**Comment by joakim-hove** [comment]
> Rather, it looks as if the ErrorContext inadvertently characterises the SUMMARY keyword itself as a UDQ keyword.

Ahhh - that might be right; I just looked through the `SPE1CASE.DATA` file and agree with you that there is nothing UDQ related there.

**Comment by bska** [comment]
Both PR #702 and PR OPM/opm-simulators#1777 have been merged.  Is this still a problem?

**Comment by bska** [comment]
I'm closing this now as no longer relevant. please reopen if the issue recurs.
