### ISSUE TITLE
Found an error on line 204 of file Aquancon.cpp

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-common#708]
Hello,

There was a compiler error from the master opm-common set of files due to a reference "&" that shouldn't/should? be there close to element1,... element2) -> bool.  Is this correct?

regards.

David

**Comment by bska** [comment]
> There was a compiler error from the master opm-common set of files due to a reference "&" that shouldn't/should? be there close to element1,... element2) -> bool. Is this correct?

Hi.

Thanks for the report.

As far as I can tell, the [current code](https://github.com/OPM/opm-common/blob/0d172c9a1c8730d802660bacccbb2aaad71a187e/src/opm/parser/eclipse/EclipseState/Aquancon.cpp#L204) does not have a syntax error although the lambda parameters could probably be references to `const` for safety reasons.  Our continuous integration service also does not find any direct issue there.  What compiler diagnostics do you get?

**Comment by dlmorenob** [comment]
I recompiled and the error is gone... its strange...thank you...I will let you know if it comes up again. sorry.

**Comment by bska** [comment]
I'm closing this as "resolved".  Please reopen if the problem recurs.
