### ISSUE TITLE
ParserKeywords .hpp files

### ISSUE THREAD

**Issue by SerNiyaz** [OPM/opm-common#714]
Hello!
I try to compile the module in Windows but I can not find the following files in the module:
```
#include <opm/parser/eclipse/Parser/ParserKeywords/A.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/C.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/D.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/G.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/I.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/M.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/P.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/R.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/S.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/T.hpp>
#include <opm/parser/eclipse/Parser/ParserKeywords/Z.hpp>
...
```

**Comment by joakim-hove** [comment]
First of all: We do not officially support Windows. It will probably be quite simple to compile on Windows but you will have to take responsibility for some changes yourself.

As for the particular error message you are listing the files you mention should be *generated* as part of the build process, so my guess is that you are not really using the cmake based build system?

**Comment by SerNiyaz** [comment]
Thank you for your prompt answer! 
When trying to build with CMake gives the following error (I have never used cmake before):

CMake Error at cmake/Modules/OpmFind.cmake:170 (find_package):
  Could not find a package configuration file provided by "ecl" with any of
  the following names:

    eclConfig.cmake
    ecl-config.cmake

  Add the installation prefix of "ecl" to CMAKE_PREFIX_PATH or set "ecl_DIR"
  to a directory containing one of the above files.  If "ecl" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  opm-common-prereqs.cmake:31 (find_package_deps)
  CMakeLists.txt:66 (include)


Configuring incomplete, errors occurred!

**Comment by alfbr** [comment]
With Windows 10 you have the usual tools available: https://docs.microsoft.com/en-us/windows/wsl/faq

Just use wsl on windows and you can follow the build instructions for Ubuntu here: https://opm-project.org/?page_id=239 We do not have the resources to support the proprietary build chain on Windows for flow. However, Resinsight (which is  desktop application and hence cannot use wsl) does support building with visual compiler and friends.

**Comment by SerNiyaz** [comment]
ok, thank you!
