### ISSUE TITLE
OPM/opm-output Eight corner points of each cell in the grid

### ISSUE THREAD

**Issue by mauriciolmatos** [OPM/opm-common#743]
Good morning everyone.

Is there an OPM output file that gives me the x, y, and z coordinates for the eight points (corners) of each cell in the grid?
The .FEGRID file only gives me COORD and ZCORN. Only with ZCORN I can't get the x and y points of the cells in the intermediate layers directly.

Thanks.

**Comment by atgeirr** [comment]
(only noticed the issue now that is was closed...)

There is no such output file, as you have noticed. However it is not so hard to write a small program (in matlab, python, c++ or whatever you prefer) that takes COORD and ZCORN, and outputs what you want. I can give you a pointer if you feel inclined.
