### ISSUE TITLE
Should doxygen really be required?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#75]
Just tested a new setup and cmake failed due to missing doxygen. Is that intended?

**Comment by akva2** [comment]
No. Forgot to test without it i guess.

-------- Opprinnelig melding --------
Fra: Markus Blatt <notifications@github.com>
Dato: 16.02.2016 19:04 (GMT+01:00)
Til: OPM/opm-common <opm-common@noreply.github.com>
Emne: [opm-common] Should doxygen really be required? (#75)


Just tested a new setup and cmake failed due to missing doxygen. Is that intended?

**Comment by joakim-hove** [comment]
<asbesto underwear on>

Everyone who has used the OPM doxygen documentation raise  their hand.

< asbesto underwear on/>
16. feb. 2016 19:04 skrev "Markus Blatt" <notifications@github.com>
følgende:

**Comment by bska** [comment]
> Everyone who has used the OPM doxygen documentation raise  their hand.

Outside of its in-source C++ comment form?

**Comment by joakim-hove** [comment]
Yes
16. feb. 2016 20:12 skrev "Bård Skaflestad" <notifications@github.com>
følgende:

**Comment by bska** [comment]
>>> Everyone who has used the OPM doxygen documentation raise  their hand.
>> 
>> Outside of its in-source C++ comment form?
>
> Yes

Well, I **have** looked at the formatted output occasionally, but mostly to verify that I didn't break it or to check the effects of certain formatting requests.  I guess that technical counts as "using it", but I certainly don't look at it with any kind of regularity outside the comment form.  That I **do** do however.

**Comment by atgeirr** [comment]
I agree that doxygen should not be required.

**Comment by andlaus** [comment]
> Everyone who has used the OPM doxygen documentation raise their hand.

 o/
/|
/ \

(at least for opm-material and ewoms.) but I think doxygen should only be an option, not a requirement.

**Comment by joakim-hove** [comment]
Hilarious ;-)
16. feb. 2016 22:44 skrev "Andreas Lauser" <notifications@github.com>
følgende:

**Comment by alfbr** [comment]
I have used it too. I don't think doxygen should be a build dependency. Whether we should ensure doxygen formatted comments/documentation is available is another discussion.

**Comment by akva2** [comment]
cannot reproduce. which unstable perturbation of the build system are you using?

**Comment by atgeirr** [comment]
Last message on this was "cannot reproduce" from @akva2, can you still produce the problem @blattms?

**Comment by pgdr** [comment]
Voting to close.

**Comment by joakim-hove** [comment]
> Voting to close.

+1
