### ISSUE TITLE
Faulty submodule configuration

### ISSUE THREAD

**Issue by markusdregi** [OPM/opm-common#803]
When I try to clone the _opm-common_ master branch with submodules I get the following error:

```
>>> git clone -q --recursive git@github.com:OPM/opm-common.git
fatal: No url found for submodule path 'python/pybind11' in .gitmodules
```

I think you need to move the `.gitmodules` file out of the `python` folder and into root.

**Comment by joakim-hove** [comment]
Ok - thank you. Observe that the Python code in opm-common is *only* copied verbatim from sunbeam, no effort has been made even to get it to compile.

That process is about to start though.

**Comment by markusdregi** [comment]
That is fair enough ;) However, I guess you do not want to break the ability to clone recursively, as this has always worked until those submodules where introduced. I can submit a suggestion in a PR.

**Comment by joakim-hove** [comment]
Actually - there is a start here: https://github.com/OPM/opm-common/pull/782 - which is not based on submodules at all.

**Comment by markusdregi** [comment]
Thanks for accepting the patch :+1:

**Comment by atgeirr** [comment]
Can this be closed, @markusdregi and @joakim-hove?
