### ISSUE TITLE
UDA and group rates

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#872]
The general UDQ machinery has now been completed, so until the implementation meets the harsh reality of a hand-made industrial deck I will assume the code Just Works&trade; - but there is more ....

**UDA in GCONxxxx**
For upcoming field studies we need to support UDA values in the `GCONxxxx` keywords - i.e. something like this:

```
UDQ
     DEFINE GUOPR1  FOPR * 0.50 /
     DEFINE GUOPR2  FOPR * 0.50 /
/

GCONPROD
   'G1'  'ORAT'  'GUOPR1' /
   'G2'  'ORAT'  'GUOPR2' /
/
```
To support this the `Group` object in opm-common needs to support late evaluation in the same way as has been implemented in the [`Well` &rightarrow; `Well2` transition](https://github.com/OPM/opm-common/pull/674). This will also require some changes in opm-simulators, these can either be minimized - or alternatively be part of a larger group (and well) refactor.

My plan is to do it in a manner quite similar to the approach used for the wells:

1. Introduce a new class `Group2`
2. Include an integrated integration test in the `Schedule` constructor which verifies that `Group`and `Group2` are equivalent.
3. Create downstream PR's using `Group2`
4. Wham-bang - change everything to use `Group2`

This job will be significantly smaller than the `Well` &rightarrow; `Well2` transition, I estimate 15 days of work on a menu of caffeine and nicotine and no hard liquor.

**Comment by atgeirr** [comment]
I think this looks like a good plan. As long as it can do with the same `SummaryState` object as is currently basis for evaluation of UDQs for the wells it should not be too hard to integrate in the simulator.

**Comment by bska** [comment]
We have the `Group2` class in place now.  Is this issue still relevant?

**Comment by joakim-hove** [comment]
> We have the Group2 class in place now. Is this issue still relevant?

Case closed - until a brutal of instance reality is encountered.
