### ISSUE TITLE
Refactor the 3D property system

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#929]
The are several problems with the 3D property system, in this issue I describe what I see as the problems and outline a possible refactoring.

#### `SuppertedKeywordInfo`: too complex

The 3D property system to handle keywords like `PORO` and `FIPNUM` is based on installing small stubs for each supported keyword - instances of `SupportedKeywordInfo`, where the `SupportedKeywordInfo` contains the name of the keyword, the dimension and function pointers to initialize and post process keywords. This works, but it is very complex and error prone.

#### Requires a full grid
The current GridProperty code requires a full `EclipseGrid` instance for the construction and processing phase, a few of the keywords actually use the the depth of cells in the initialization, but for most of the keywords only the grid dimensions are required. That the implementation requires a full `EclipseGrid` creates some Catch22 situations.

### Suggested refactoring
I suggest completely removing the `SupportedKeywordInfo` structure, and instead make one large function:
```C++
std::vector<data> Eclipse3DProperty.get(const std::string& keyword) {
    
     if (keyword == "PORO") {
         ....
     } else if (keyword == "PERMX") { 
         ....
     }  else if (keyword == "PERMZ") {
         ...
```
might seem a primitive way to do it - but I actually think this will be a significant improvement.

**Comment by bska** [comment]
I haven't thought through your proposal at all, but the one thing that really bugs me about the current system is the fact that we always store `nx * ny * nz` cell values for each property, even after the model is compressed to active cells only.  If we're going to do something about the property system I'd really like it fi we could look into storing values only for the active cells.

**Comment by joakim-hove** [comment]
Regarding storing only active values: are you mostly concerned with storage space or convenience?

**Comment by bska** [comment]
> are you mostly concerned with storage space or convenience?

Yes :smile:

Seriously, I do care mostly about space savings in this context. I also want to discourage loops over the Cartesian cells and if making property lookup based on Cartesian index harder has that effect, then that's welcome too.

**Comment by joakim-hove** [comment]
> I do care mostly about space savings in this context. I also want to discourage loops over the Cartesian cells

I see. During the construction phase it is certainly easier - maybe even necessary - to work with the full `nx*ny*nz` - but when the dust has settled, all modifers been applied and so on one could certainly switch to only working with active cells. Maybe one could envision an implementation where only code in opm-common had access to cartesian functionality, and that the public API serving data out of opm-common would only serve active cells; i.e. the only exported access point could be:
```
template <typename T>
std::vector<T> container.get(const std::string& keyword, const EclipseGrid& grid) {

}
```
To really reduce memory I think calling scope would have to issue some kind of `.release()` command, or alternatively the properties must be ripped out of `EclipseState` and be owned by the calling scope?

**Comment by bska** [comment]
Just following up here&mdash;sorry about the delayed response.

> To really reduce memory I think calling scope would have to issue some kind of `.release()` command, or alternatively the properties must be ripped out of `EclipseState` and be owned by the calling scope?

I did envision a function of the form `EclipseState::compress(activeCells)` to facilitate the actual (and permanent) memory reduction once the set of active cells is established (and the `.EGRID` file is written).  That call would apply to the 3D properties.

As a second step we might even consider extending the `compress` operation to apply to the grid itself (i.e., discarding information about all inactive cells).  This might possibly entail decoupling the `EclipseGrid` from libecl and would therefore be a substantial amount of work.

**Comment by bska** [comment]
I believe we've addressed most of the questions raised in this issue.  Is this still relevant?

**Comment by bska** [comment]
I'm closing this now.  We're not going to do more in this particular direction.
