### ISSUE TITLE
Simulations with RESTART keyword are throwing exceptions.

### ISSUE THREAD

**Issue by emanuelbarroso** [OPM/opm-common#956]
Basically, whenever I try to run a simulation with a restart setting, opm throws an exception and does not state what is wrong. It says that the problem could not be initialized.

**Comment by emanuelbarroso** [comment]
Basically, whenever I try to run a simulation with a restart setting, opm throws an exception and does not state what is wrong.

**Comment by joakim-hove** [comment]
Do you have any error messages?

**Comment by emanuelbarroso** [comment]
![error](https://user-images.githubusercontent.com/3778448/63167960-2df85980-c009-11e9-96cc-d311d2726598.png)

**Comment by GitPaean** [comment]
Are you using some certain release version or compiling from the source code?

**Comment by joakim-hove** [comment]
OK - not that I think that is the problem; but you seem to be running from the inside of Python in some way. Could you run again from the shell - without any Python wrapper. If you could show the part of the deck with the `"RESTART"` keyword that might help.

**Comment by emanuelbarroso** [comment]
![error2](https://user-images.githubusercontent.com/3778448/63168455-93007f00-c00a-11e9-812b-e26262c99de9.png)

Now, the deck.zip. It contains 0EGG.DATA (without restart) and ITER1I1.DATA (with it).
[DECK.zip](https://github.com/OPM/opm-common/files/3509612/DECK.zip)

**Comment by GitPaean** [comment]
From my side, without changing any DATA file, I just add the running argument 

`flow  0EGG.DATA --output-dir=DUMP`

It looks like running. 

As a result, it is basically about how to specify the folder of the RESTART file.

**Comment by emanuelbarroso** [comment]
try running ITER1I1.DATA

**Comment by GitPaean** [comment]
it runs. while I am not using any release version. I compile from the source code. Not sure it is a problem in the release version. 

Anyway, for the wrong directory problem, we should be able to give some meaningful error message.

**Comment by emanuelbarroso** [comment]
the problem is, I'm using the output-dir option correctly. And it was working until my opm was updated some time ago.

**Comment by GitPaean** [comment]
Can you check whether in the DUMP folder, you can see all the following files?

`0EGG.DBG  0EGG.EGRID  0EGG.INIT  0EGG.PRT  0EGG.S0001  0EGG.SMSPEC  0EGG.X0000  0EGG.X0001
`

**Comment by emanuelbarroso** [comment]
They're all in there.

**Comment by emanuelbarroso** [comment]
just out of curiosity, could someone provide me a binary of an earlier version of OPM?

**Comment by emanuelbarroso** [comment]
Ok, gentlemen, I made it work. Thanks for the attention.
